$axure.loadCurrentPage({
  "url":"盘点.html",
  "generationDate":new Date(1473153213328.57),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"47fea96ebc3d41a8b915f420ca15744e",
    "type":"Axure:Page",
    "name":"盘点",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"81ac40106a3f430693cc2b3bd2795198",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":1254,
              "height":890},
            "borderWidth":"2",
            "cornerRadiusTopLeft":"57"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b039a09b0f4488e81ca542d72052819",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":1254,
                  "height":890},
                "borderWidth":"2",
                "cornerRadiusTopLeft":"57"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u0.png"}},
{
          "id":"824503f8a3964526bd3adeb269aa0f6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":115,
              "y":60},
            "size":{
              "width":1024,
              "height":768},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66671094b91d424b8de679b59e30f2ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":115,
                  "y":60},
                "size":{
                  "width":1024,
                  "height":768},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u2.png"}},
{
          "id":"2be820803760468abeb93f2b9f1bff3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1160,
              "y":410},
            "size":{
              "width":70,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494},
            "cornerRadiusTopLeft":"40"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"daaa499cc94c4cd5954b7ebd15629d06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1160,
                  "y":410},
                "size":{
                  "width":70,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494},
                "cornerRadiusTopLeft":"40"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u4.png"}},
{
          "id":"9d48a186c4a440adacbc603eca026f49",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":193},
            "size":{
              "width":936,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/查询结果/u10_line.png"}},
{
          "id":"d636cabcfbb64fa983b7629295be6fd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":547,
              "y":745},
            "size":{
              "width":160,
              "height":35},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0bf6fcf4766496b9e8503a5dc8a3bb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":547,
                  "y":745},
                "size":{
                  "width":160,
                  "height":35},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/库存预警/u7.png"}},
{
          "id":"5cc2d11b41c543b2a8f6b6a4c8ca2254",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":159,
              "y":95},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e9b99fa365a44fa8a39301e645335d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":159,
                  "y":95},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e2911afd6df4abd90fa6ef0ad93f81f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":159,
              "y":132},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e423e252c2640faabae8375020c7bbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":159,
                  "y":132},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"773bbdf02a4546df931909034c40fe7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":218,
              "y":132},
            "size":{
              "width":124,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f996ac85a1a4eaf89f12d2d0f87f27f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":218,
                  "y":132},
                "size":{
                  "width":124,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5610add107f430aa69dbac015d6d58b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":159,
              "y":164},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7000936bfc2e4517ae7d98f9f1215891",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":159,
                  "y":164},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5df171371e23455084099daa977812ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":218,
              "y":164},
            "size":{
              "width":153,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99d2fa42510c4f4198d6a285c6acdc50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":218,
                  "y":164},
                "size":{
                  "width":153,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0f6642692d0648838a876146e1d9b6c1",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":213},
            "size":{
              "width":936,
              "height":192}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb6db3f4429844f79e9eed3fefa80f48",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":211,
                  "height":42},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3a9fc153229647aa93d45ee2b1ae4d71",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"12px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":211,
                      "height":42},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点/u20.png"}},
{
              "id":"6cbdf853392e44e1add76bc130363f40",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":42},
                "size":{
                  "width":211,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0ad326138a8d46c9b813d70c3fe75fff",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":42},
                    "size":{
                      "width":211,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点/u28.png"}},
{
              "id":"47e1edd4e6c448c98cee6432653dba59",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":92},
                "size":{
                  "width":211,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8a1e3ff574aa49d593842a59d58fdaf3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":92},
                    "size":{
                      "width":211,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点/u28.png"}},
{
              "id":"b6a86d6563874d9dbc28583e59304f45",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":211,
                  "y":0},
                "size":{
                  "width":231,
                  "height":42},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"158bc293501f430ebb9d1cf7dc27c8b9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"12px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":211,
                      "y":0},
                    "size":{
                      "width":231,
                      "height":42},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点/u22.png"}},
{
              "id":"f13c0d329c5e4c288a47a904ce2108de",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":211,
                  "y":42},
                "size":{
                  "width":231,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ffb3904aae4a45cd8d511fe57525743b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":211,
                      "y":42},
                    "size":{
                      "width":231,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点/u30.png"}},
{
              "id":"407859f29d7f401f800a9df8c66b0933",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":211,
                  "y":92},
                "size":{
                  "width":231,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9097e86f598d46db89302a512a7bf947",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":211,
                      "y":92},
                    "size":{
                      "width":231,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点/u30.png"}},
{
              "id":"acf52ef6a4d54676965275edfcd81d42",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":142},
                "size":{
                  "width":211,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cab22ae55c2e4c398e7675824ee4c0ba",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":142},
                    "size":{
                      "width":211,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点/u28.png"}},
{
              "id":"0229fc6e5b6d40faa9c8d1e6e1823caf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":211,
                  "y":142},
                "size":{
                  "width":231,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7821bf89a8d943fcbff6d7a72fa323ff",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":211,
                      "y":142},
                    "size":{
                      "width":231,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点/u30.png"}},
{
              "id":"c404f3be8eaf4327923a73d943cf5661",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":442,
                  "y":0},
                "size":{
                  "width":259,
                  "height":42},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ef65cd48ab4843c4b465e6571ce4ccf1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"12px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":442,
                      "y":0},
                    "size":{
                      "width":259,
                      "height":42},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点/u24.png"}},
{
              "id":"3d9ac005171e4bfe89f1773055df28b2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":442,
                  "y":42},
                "size":{
                  "width":259,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ef94b985930f4751acdb45a1d7684e29",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":442,
                      "y":42},
                    "size":{
                      "width":259,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点/u32.png"}},
{
              "id":"e9fe1d6d7d1c46bd9bce60dfaa40f1f6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":442,
                  "y":92},
                "size":{
                  "width":259,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"42ce506513064f29936650aa03dfb7a7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":442,
                      "y":92},
                    "size":{
                      "width":259,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点/u32.png"}},
{
              "id":"a02df0a744ce4d01981128315a7112c7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":442,
                  "y":142},
                "size":{
                  "width":259,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"534dc9ebcdb14c95a823da1a31886a27",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":442,
                      "y":142},
                    "size":{
                      "width":259,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点/u32.png"}},
{
              "id":"4da78befda504979812255ab8c26bb51",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":701,
                  "y":0},
                "size":{
                  "width":235,
                  "height":42},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ea8eddc9a0654d6197c6a74b2cd72fc5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"12px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":701,
                      "y":0},
                    "size":{
                      "width":235,
                      "height":42},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点/u26.png"}},
{
              "id":"a3029a7da23343a3869beb00a3f2042e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":701,
                  "y":42},
                "size":{
                  "width":235,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a8fd70601c4e42df9272bc949fea5160",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":701,
                      "y":42},
                    "size":{
                      "width":235,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点/u34.png"}},
{
              "id":"47b9e67993764e5183ad94622fb3ed4f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":701,
                  "y":92},
                "size":{
                  "width":235,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ed39bb3710ce44d685f0aaac412ce2a9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":701,
                      "y":92},
                    "size":{
                      "width":235,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点/u34.png"}},
{
              "id":"444fef71f7f34490925d6cbbaaf4a7f7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":701,
                  "y":142},
                "size":{
                  "width":235,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b6d4451797de412bb1cd0381924687ed",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":701,
                      "y":142},
                    "size":{
                      "width":235,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点/u34.png"}}]},
{
          "id":"fc649f0ea58f4620973ff574c569718f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":297},
            "size":{
              "width":936,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/查询结果/u52_line.png"}},
{
          "id":"4270ec42f5b64200814b5909ae961b2e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":346},
            "size":{
              "width":936,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/查询结果/u52_line.png"}},
{
          "id":"086139ba4dcd4aa1946d0e115a2fe321",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":397},
            "size":{
              "width":936,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/查询结果/u52_line.png"}},
{
          "id":"8e48c27a42e44a358d9bbaef093c5df1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":377,
              "y":960},
            "size":{
              "width":500,
              "height":300},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b36f4f4e8384208bf795667be20d090",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":377,
                  "y":960},
                "size":{
                  "width":500,
                  "height":300},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/紧急订货/u66.png"}},
{
          "id":"f9785bc51d6143358ba30f9a77bb0cc2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":377,
              "y":1015},
            "size":{
              "width":500,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/紧急订货/u68_line.png"}},
{
          "id":"42f505fd4aed42f4b931e2bc5c0c0384",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":391,
              "y":980},
            "size":{
              "width":129,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee0741b661f246d7b2967fb177622507",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":391,
                  "y":980},
                "size":{
                  "width":129,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2c46d9e9e9c4f78886922e6f4701bf9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":512,
              "y":1190},
            "size":{
              "width":123,
              "height":35},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a586bb302c214599b2feccbe99298f6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":512,
                  "y":1190},
                "size":{
                  "width":123,
                  "height":35},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/紧急订货/u71.png"}},
{
          "id":"72a5d95b29fc4c6387c20c6880eedba5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":645,
              "y":1190},
            "size":{
              "width":97,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e04e258c04b449b995c141b9f98a201b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":645,
                  "y":1190},
                "size":{
                  "width":97,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/盘点/u62.png"}},
{
          "id":"da43b36a489c4a5e817c89a85518b602",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":622,
              "y":790},
            "size":{
              "width":10,
              "height":160},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/紧急订货/u65_end.png",
            "line~":"images/紧急订货/u65_line.png"}},
{
          "id":"428a5f2f28a94abd82b9f8184a11f6a9",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":432,
              "y":1086},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c204051d992a4f91953757c14a9d168c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":432,
                  "y":1086},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"30d36ddc25b148fabe712835ade53f0f",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":577,
              "y":1086},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81badb6eee3543cca2bfdd0a611884be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":577,
                  "y":1086},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"6e385ea251a44191a9f7d3ea2df647df",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":722,
              "y":1086},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd83c8ec48714722a822d53d60bba672",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":722,
                  "y":1086},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"60f33963e8c04f8e9bbd05936efffff6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":843,
              "y":973},
            "size":{
              "width":17,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d74e3fdfb1b5416f9f7a7444a25a3f7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":843,
                  "y":973},
                "size":{
                  "width":17,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9c5c349b6234a82a86a39fa0032eac3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":914,
              "y":1015},
            "size":{
              "width":196,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48e47cabcddb49b783d3653b5af4058d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":914,
                  "y":1015},
                "size":{
                  "width":196,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "81ac40106a3f430693cc2b3bd2795198":{
      "scriptId":"u0"},
    "7b039a09b0f4488e81ca542d72052819":{
      "scriptId":"u1"},
    "824503f8a3964526bd3adeb269aa0f6f":{
      "scriptId":"u2"},
    "66671094b91d424b8de679b59e30f2ec":{
      "scriptId":"u3"},
    "2be820803760468abeb93f2b9f1bff3c":{
      "scriptId":"u4"},
    "daaa499cc94c4cd5954b7ebd15629d06":{
      "scriptId":"u5"},
    "9d48a186c4a440adacbc603eca026f49":{
      "scriptId":"u6"},
    "d636cabcfbb64fa983b7629295be6fd3":{
      "scriptId":"u7"},
    "d0bf6fcf4766496b9e8503a5dc8a3bb6":{
      "scriptId":"u8"},
    "5cc2d11b41c543b2a8f6b6a4c8ca2254":{
      "scriptId":"u9"},
    "8e9b99fa365a44fa8a39301e645335d5":{
      "scriptId":"u10"},
    "7e2911afd6df4abd90fa6ef0ad93f81f":{
      "scriptId":"u11"},
    "1e423e252c2640faabae8375020c7bbd":{
      "scriptId":"u12"},
    "773bbdf02a4546df931909034c40fe7f":{
      "scriptId":"u13"},
    "6f996ac85a1a4eaf89f12d2d0f87f27f":{
      "scriptId":"u14"},
    "b5610add107f430aa69dbac015d6d58b":{
      "scriptId":"u15"},
    "7000936bfc2e4517ae7d98f9f1215891":{
      "scriptId":"u16"},
    "5df171371e23455084099daa977812ee":{
      "scriptId":"u17"},
    "99d2fa42510c4f4198d6a285c6acdc50":{
      "scriptId":"u18"},
    "0f6642692d0648838a876146e1d9b6c1":{
      "scriptId":"u19"},
    "fb6db3f4429844f79e9eed3fefa80f48":{
      "scriptId":"u20"},
    "3a9fc153229647aa93d45ee2b1ae4d71":{
      "scriptId":"u21"},
    "b6a86d6563874d9dbc28583e59304f45":{
      "scriptId":"u22"},
    "158bc293501f430ebb9d1cf7dc27c8b9":{
      "scriptId":"u23"},
    "c404f3be8eaf4327923a73d943cf5661":{
      "scriptId":"u24"},
    "ef65cd48ab4843c4b465e6571ce4ccf1":{
      "scriptId":"u25"},
    "4da78befda504979812255ab8c26bb51":{
      "scriptId":"u26"},
    "ea8eddc9a0654d6197c6a74b2cd72fc5":{
      "scriptId":"u27"},
    "6cbdf853392e44e1add76bc130363f40":{
      "scriptId":"u28"},
    "0ad326138a8d46c9b813d70c3fe75fff":{
      "scriptId":"u29"},
    "f13c0d329c5e4c288a47a904ce2108de":{
      "scriptId":"u30"},
    "ffb3904aae4a45cd8d511fe57525743b":{
      "scriptId":"u31"},
    "3d9ac005171e4bfe89f1773055df28b2":{
      "scriptId":"u32"},
    "ef94b985930f4751acdb45a1d7684e29":{
      "scriptId":"u33"},
    "a3029a7da23343a3869beb00a3f2042e":{
      "scriptId":"u34"},
    "a8fd70601c4e42df9272bc949fea5160":{
      "scriptId":"u35"},
    "47e1edd4e6c448c98cee6432653dba59":{
      "scriptId":"u36"},
    "8a1e3ff574aa49d593842a59d58fdaf3":{
      "scriptId":"u37"},
    "407859f29d7f401f800a9df8c66b0933":{
      "scriptId":"u38"},
    "9097e86f598d46db89302a512a7bf947":{
      "scriptId":"u39"},
    "e9fe1d6d7d1c46bd9bce60dfaa40f1f6":{
      "scriptId":"u40"},
    "42ce506513064f29936650aa03dfb7a7":{
      "scriptId":"u41"},
    "47b9e67993764e5183ad94622fb3ed4f":{
      "scriptId":"u42"},
    "ed39bb3710ce44d685f0aaac412ce2a9":{
      "scriptId":"u43"},
    "acf52ef6a4d54676965275edfcd81d42":{
      "scriptId":"u44"},
    "cab22ae55c2e4c398e7675824ee4c0ba":{
      "scriptId":"u45"},
    "0229fc6e5b6d40faa9c8d1e6e1823caf":{
      "scriptId":"u46"},
    "7821bf89a8d943fcbff6d7a72fa323ff":{
      "scriptId":"u47"},
    "a02df0a744ce4d01981128315a7112c7":{
      "scriptId":"u48"},
    "534dc9ebcdb14c95a823da1a31886a27":{
      "scriptId":"u49"},
    "444fef71f7f34490925d6cbbaaf4a7f7":{
      "scriptId":"u50"},
    "b6d4451797de412bb1cd0381924687ed":{
      "scriptId":"u51"},
    "fc649f0ea58f4620973ff574c569718f":{
      "scriptId":"u52"},
    "4270ec42f5b64200814b5909ae961b2e":{
      "scriptId":"u53"},
    "086139ba4dcd4aa1946d0e115a2fe321":{
      "scriptId":"u54"},
    "8e48c27a42e44a358d9bbaef093c5df1":{
      "scriptId":"u55"},
    "1b36f4f4e8384208bf795667be20d090":{
      "scriptId":"u56"},
    "f9785bc51d6143358ba30f9a77bb0cc2":{
      "scriptId":"u57"},
    "42f505fd4aed42f4b931e2bc5c0c0384":{
      "scriptId":"u58"},
    "ee0741b661f246d7b2967fb177622507":{
      "scriptId":"u59"},
    "e2c46d9e9e9c4f78886922e6f4701bf9":{
      "scriptId":"u60"},
    "a586bb302c214599b2feccbe99298f6c":{
      "scriptId":"u61"},
    "72a5d95b29fc4c6387c20c6880eedba5":{
      "scriptId":"u62"},
    "e04e258c04b449b995c141b9f98a201b":{
      "scriptId":"u63"},
    "da43b36a489c4a5e817c89a85518b602":{
      "scriptId":"u64"},
    "428a5f2f28a94abd82b9f8184a11f6a9":{
      "scriptId":"u65"},
    "c204051d992a4f91953757c14a9d168c":{
      "scriptId":"u66"},
    "30d36ddc25b148fabe712835ade53f0f":{
      "scriptId":"u67"},
    "81badb6eee3543cca2bfdd0a611884be":{
      "scriptId":"u68"},
    "6e385ea251a44191a9f7d3ea2df647df":{
      "scriptId":"u69"},
    "fd83c8ec48714722a822d53d60bba672":{
      "scriptId":"u70"},
    "60f33963e8c04f8e9bbd05936efffff6":{
      "scriptId":"u71"},
    "d74e3fdfb1b5416f9f7a7444a25a3f7c":{
      "scriptId":"u72"},
    "d9c5c349b6234a82a86a39fa0032eac3":{
      "scriptId":"u73"},
    "48e47cabcddb49b783d3653b5af4058d":{
      "scriptId":"u74"}}});