$axure.loadCurrentPage({
  "url":"入库单详情.html",
  "generationDate":new Date(1473153212859.65),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"31da6f6516b64da1842692c67d8baf7c",
    "type":"Axure:Page",
    "name":"入库单详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f0c956d995dc4e22b1ea8e9a7ce116ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":1254,
              "height":890},
            "borderWidth":"2",
            "cornerRadiusTopLeft":"57"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de7700ac6f3248d9ad389ba94601e492",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":1254,
                  "height":890},
                "borderWidth":"2",
                "cornerRadiusTopLeft":"57"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u0.png"}},
{
          "id":"3f25aa8f1ab64e54a197a1cbf9ef4ff5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":115,
              "y":60},
            "size":{
              "width":1024,
              "height":768},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54a8daf5e577402792a09f99d66540f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":115,
                  "y":60},
                "size":{
                  "width":1024,
                  "height":768},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u2.png"}},
{
          "id":"ec08a30c2bdb48c580f14f90c2d899e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1160,
              "y":410},
            "size":{
              "width":70,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494},
            "cornerRadiusTopLeft":"40"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf3f7206835d48adbcc246452f378bc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1160,
                  "y":410},
                "size":{
                  "width":70,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494},
                "cornerRadiusTopLeft":"40"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u4.png"}},
{
          "id":"02b8f48275f943169ba829b6d1e72f9b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":120},
            "size":{
              "width":936,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/查询结果/u10_line.png"}},
{
          "id":"47a3e03132e34183b3f124fcc15bfa04",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":160},
            "size":{
              "width":936,
              "height":192}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25cddc0f2e7a47a8a98023b98a3014f6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":169,
                  "height":42},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4396a9450c7e4004bd35ff6bfc889e57",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"12px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":169,
                      "height":42},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库单详情/u8.png"}},
{
              "id":"c8b13dd67d374eb787845bb182c13ab2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":42},
                "size":{
                  "width":169,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c098cd97f9a74873847d9c5cb20a47b1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":42},
                    "size":{
                      "width":169,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库单详情/u16.png"}},
{
              "id":"a0271a360c89438789c4dfc247a08563",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":92},
                "size":{
                  "width":169,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c19ff30907a743a8aa785ccb88ad314b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":92},
                    "size":{
                      "width":169,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库单详情/u16.png"}},
{
              "id":"f8c422fd81914bd6bf3c9139736551c1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":169,
                  "y":0},
                "size":{
                  "width":376,
                  "height":42},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b9c478b18fc9402189945e5c27b58d44",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"12px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":169,
                      "y":0},
                    "size":{
                      "width":376,
                      "height":42},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库单详情/u10.png"}},
{
              "id":"2b81407c031e45ab84b0bb7aacfea79b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":169,
                  "y":42},
                "size":{
                  "width":376,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eb55f43cae894f46a4290060dbaa97e7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":169,
                      "y":42},
                    "size":{
                      "width":376,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库单详情/u18.png"}},
{
              "id":"b910860588a3430bbb3a7ff8a4812bbc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":169,
                  "y":92},
                "size":{
                  "width":376,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0be376b834d04002b8f340e29fc87c66",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":169,
                      "y":92},
                    "size":{
                      "width":376,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库单详情/u18.png"}},
{
              "id":"0272a0d5db4b443b9b2c8de212699c2a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":142},
                "size":{
                  "width":169,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"47dc98474ee648dfb372c869d2ab2cff",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":142},
                    "size":{
                      "width":169,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库单详情/u16.png"}},
{
              "id":"9eaad6c5a8d34b1888464bb79fdd42f9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":169,
                  "y":142},
                "size":{
                  "width":376,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e356fe21d20841e9b1fe899a1b5d65a8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":169,
                      "y":142},
                    "size":{
                      "width":376,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库单详情/u18.png"}},
{
              "id":"d420198b228743eb92fb9a2684867cb2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":545,
                  "y":0},
                "size":{
                  "width":184,
                  "height":42},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4d1e3b4f826e4b96994773e05cc2c4fa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"12px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":545,
                      "y":0},
                    "size":{
                      "width":184,
                      "height":42},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库存预警/u18.png"}},
{
              "id":"055f1f5fc15f48d8b73b74e0c03df769",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":545,
                  "y":42},
                "size":{
                  "width":184,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8fce53ceb4e7419ba4a857663e9bad09",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":545,
                      "y":42},
                    "size":{
                      "width":184,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库存预警/u28.png"}},
{
              "id":"8b77d1a7843746db88cba8965bcd9277",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":545,
                  "y":92},
                "size":{
                  "width":184,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8a7136b1980f41f8862249900729f1d9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":545,
                      "y":92},
                    "size":{
                      "width":184,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库存预警/u28.png"}},
{
              "id":"f3a602b2c6da4cf7bfba27334b7b2175",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":545,
                  "y":142},
                "size":{
                  "width":184,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dbccbd0c980f41489ae146c8fdac9d2a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":545,
                      "y":142},
                    "size":{
                      "width":184,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库存预警/u28.png"}},
{
              "id":"44c700eec3b441a19acc2246fe6b2228",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":729,
                  "y":0},
                "size":{
                  "width":207,
                  "height":42},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e667a0777a564b5a861bf8dc4e547edc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"12px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":729,
                      "y":0},
                    "size":{
                      "width":207,
                      "height":42},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库单详情/u14.png"}},
{
              "id":"e63c1b5bff1b40ca8f857b8e927fcb30",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":729,
                  "y":42},
                "size":{
                  "width":207,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5d1b978dde3a443fbe8a1c01a92f9903",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":729,
                      "y":42},
                    "size":{
                      "width":207,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库单详情/u22.png"}},
{
              "id":"21cc7c4a42864e40a46cafee5964ace8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":729,
                  "y":92},
                "size":{
                  "width":207,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"daa51ce6b229448fa5b9e79cd1a8b1d5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":729,
                      "y":92},
                    "size":{
                      "width":207,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库单详情/u22.png"}},
{
              "id":"d3d4b3f78af1456d9b2c652473d1ae68",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":729,
                  "y":142},
                "size":{
                  "width":207,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3d771c31d37d4e6a81f286f6cdd50174",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":729,
                      "y":142},
                    "size":{
                      "width":207,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库单详情/u22.png"}}]},
{
          "id":"ad96a5040da44f4f869ff7d5ff6d9251",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":168,
              "y":88},
            "size":{
              "width":146,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2c1842e82f742c589162f02259f6c7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":168,
                  "y":88},
                "size":{
                  "width":146,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6212aa04411d4726bbf88225ff2d4d0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":340,
              "y":87},
            "size":{
              "width":59,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"605c1f0cfb2a4e0c959f83d031eb55c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":340,
                  "y":87},
                "size":{
                  "width":59,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入库/u20.png"}},
{
          "id":"480a3806a5ab49928b96b00e31c7fe4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9,
              "opacity":1},
            "location":{
              "x":440,
              "y":88},
            "size":{
              "width":174,
              "height":15},
            "borderWidth":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf5adfe866154ae381df9ab895831758",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9,
                  "opacity":1},
                "location":{
                  "x":440,
                  "y":88},
                "size":{
                  "width":174,
                  "height":15},
                "borderWidth":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ef150ecd7b140ca9fbd5085643ded13",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":547,
              "y":745},
            "size":{
              "width":160,
              "height":35},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e17b8aabc2449bd9f2f36f1b8e44854",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":547,
                  "y":745},
                "size":{
                  "width":160,
                  "height":35},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/库存预警/u7.png"}},
{
          "id":"9126740b1cc64e5dbfe803399afdb729",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":244},
            "size":{
              "width":936,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/查询结果/u52_line.png"}},
{
          "id":"eb78b99102c743188920720ab3b36447",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":293},
            "size":{
              "width":936,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/查询结果/u52_line.png"}},
{
          "id":"7adcaf6ea40c44ca822ccab373751e59",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":344},
            "size":{
              "width":936,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/查询结果/u52_line.png"}},
{
          "id":"6fc588035d3e4d818246e45997f46d62",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF9999FF,
              "opacity":1},
            "location":{
              "x":1051,
              "y":87},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf5170e5e1e7427cbb9125d3493cff29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF9999FF,
                  "opacity":1},
                "location":{
                  "x":1051,
                  "y":87},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f35ff69060364fdba084f09c2d62769d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1293,
              "y":63},
            "size":{
              "width":378,
              "height":764},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6f2ac60e7b6422ea02a13fe87afd275",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1293,
                  "y":63},
                "size":{
                  "width":378,
                  "height":764},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入库单详情/u53.png"}},
{
          "id":"810503aed3054504bc7a5034ea885d93",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":1447,
              "y":88},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c7dac4dedfd4de6a7bef6290ba23c5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":1447,
                  "y":88},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5dca9810d966448697a525e31e26efe4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1304,
              "y":129},
            "size":{
              "width":360,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/入库单详情/u57_line.png"}},
{
          "id":"4a02fc63c2444250bad5a49ab4a069fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":1317,
              "y":84},
            "size":{
              "width":17,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d1e465849a641af976f5c0f5d58307c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":1317,
                  "y":84},
                "size":{
                  "width":17,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"137da3f5f6d644a1a5f361fcc8fa9da1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":1343,
              "y":170},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd501547307f4ceb84f891ac2d76b5d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":1343,
                  "y":170},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d93f47c421f47da8ac74362767aae3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":1343,
              "y":196},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a551be0d9a904ec681e53e3c0a134bfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":1343,
                  "y":196},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aaae3f0ac1f34230a29428e8736df268",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":1343,
              "y":222},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71c4482fb4c24732a5c2bd56fcd5d0ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":1343,
                  "y":222},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29fcc9fd0b5849ff90bdf90bfd647beb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":1369,
              "y":248},
            "size":{
              "width":25,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"045f1b6bb5ed443083cc084b3833ca8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":1369,
                  "y":248},
                "size":{
                  "width":25,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b5cc7b31c0c4a4e9db752764f9ef5b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1429,
              "y":170},
            "size":{
              "width":184,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35b8f2973b324c0d9916670bc2a1092e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1429,
                  "y":170},
                "size":{
                  "width":184,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3aec2141ed7451e97e7d3a4e5b47462",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1429,
              "y":196},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0d07f7929c3449fb0005c9c3da778e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1429,
                  "y":196},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe638aa8ece44a3eafdd2d3798a900b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1429,
              "y":222},
            "size":{
              "width":79,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b16f01edb37b4ebf9b59ca8f4f3c05cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1429,
                  "y":222},
                "size":{
                  "width":79,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ed3c1867f54497887d79e8334f6bfa7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1429,
              "y":248},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4f743a6e14a4495a7becb65b3cbaf25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1429,
                  "y":248},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d7265850dbb6469bb38048c9f6b626dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":1369,
              "y":274},
            "size":{
              "width":25,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"120f4739ef0945dea0a01fcc9dc44e47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":1369,
                  "y":274},
                "size":{
                  "width":25,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6113df95a7241f28382570ca073dfbd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1429,
              "y":274},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b4a603dacf24b5986322d415a18483c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1429,
                  "y":274},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6a881c675374f2893372107adfbd53c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":1357,
              "y":300},
            "size":{
              "width":37,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fead37990d64e1ab817af96107e28dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":1357,
                  "y":300},
                "size":{
                  "width":37,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"693a5a19d57d4316b8448e5f003560ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1429,
              "y":300},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c092cf041192485b9bedeedac445ccdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1429,
                  "y":300},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"79ba1feff7764cc3af412d545afe4a50",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":1319,
              "y":325},
            "size":{
              "width":73,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc6ddd902e204774a0a59ebe8ec01a29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":1319,
                  "y":325},
                "size":{
                  "width":73,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c97f0f057c1248a283774f8eaeac4930",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1429,
              "y":326},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c80444eb8414cde96e2d4376af1bfc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1429,
                  "y":326},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"875c2ba3bfa14edeb329c83021e52990",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1114,
              "y":90},
            "size":{
              "width":169,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/紧急订货/u87_end.png",
            "line~":"images/入库单详情/u88_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f0c956d995dc4e22b1ea8e9a7ce116ca":{
      "scriptId":"u0"},
    "de7700ac6f3248d9ad389ba94601e492":{
      "scriptId":"u1"},
    "3f25aa8f1ab64e54a197a1cbf9ef4ff5":{
      "scriptId":"u2"},
    "54a8daf5e577402792a09f99d66540f9":{
      "scriptId":"u3"},
    "ec08a30c2bdb48c580f14f90c2d899e7":{
      "scriptId":"u4"},
    "bf3f7206835d48adbcc246452f378bc8":{
      "scriptId":"u5"},
    "02b8f48275f943169ba829b6d1e72f9b":{
      "scriptId":"u6"},
    "47a3e03132e34183b3f124fcc15bfa04":{
      "scriptId":"u7"},
    "25cddc0f2e7a47a8a98023b98a3014f6":{
      "scriptId":"u8"},
    "4396a9450c7e4004bd35ff6bfc889e57":{
      "scriptId":"u9"},
    "f8c422fd81914bd6bf3c9139736551c1":{
      "scriptId":"u10"},
    "b9c478b18fc9402189945e5c27b58d44":{
      "scriptId":"u11"},
    "d420198b228743eb92fb9a2684867cb2":{
      "scriptId":"u12"},
    "4d1e3b4f826e4b96994773e05cc2c4fa":{
      "scriptId":"u13"},
    "44c700eec3b441a19acc2246fe6b2228":{
      "scriptId":"u14"},
    "e667a0777a564b5a861bf8dc4e547edc":{
      "scriptId":"u15"},
    "c8b13dd67d374eb787845bb182c13ab2":{
      "scriptId":"u16"},
    "c098cd97f9a74873847d9c5cb20a47b1":{
      "scriptId":"u17"},
    "2b81407c031e45ab84b0bb7aacfea79b":{
      "scriptId":"u18"},
    "eb55f43cae894f46a4290060dbaa97e7":{
      "scriptId":"u19"},
    "055f1f5fc15f48d8b73b74e0c03df769":{
      "scriptId":"u20"},
    "8fce53ceb4e7419ba4a857663e9bad09":{
      "scriptId":"u21"},
    "e63c1b5bff1b40ca8f857b8e927fcb30":{
      "scriptId":"u22"},
    "5d1b978dde3a443fbe8a1c01a92f9903":{
      "scriptId":"u23"},
    "a0271a360c89438789c4dfc247a08563":{
      "scriptId":"u24"},
    "c19ff30907a743a8aa785ccb88ad314b":{
      "scriptId":"u25"},
    "b910860588a3430bbb3a7ff8a4812bbc":{
      "scriptId":"u26"},
    "0be376b834d04002b8f340e29fc87c66":{
      "scriptId":"u27"},
    "8b77d1a7843746db88cba8965bcd9277":{
      "scriptId":"u28"},
    "8a7136b1980f41f8862249900729f1d9":{
      "scriptId":"u29"},
    "21cc7c4a42864e40a46cafee5964ace8":{
      "scriptId":"u30"},
    "daa51ce6b229448fa5b9e79cd1a8b1d5":{
      "scriptId":"u31"},
    "0272a0d5db4b443b9b2c8de212699c2a":{
      "scriptId":"u32"},
    "47dc98474ee648dfb372c869d2ab2cff":{
      "scriptId":"u33"},
    "9eaad6c5a8d34b1888464bb79fdd42f9":{
      "scriptId":"u34"},
    "e356fe21d20841e9b1fe899a1b5d65a8":{
      "scriptId":"u35"},
    "f3a602b2c6da4cf7bfba27334b7b2175":{
      "scriptId":"u36"},
    "dbccbd0c980f41489ae146c8fdac9d2a":{
      "scriptId":"u37"},
    "d3d4b3f78af1456d9b2c652473d1ae68":{
      "scriptId":"u38"},
    "3d771c31d37d4e6a81f286f6cdd50174":{
      "scriptId":"u39"},
    "ad96a5040da44f4f869ff7d5ff6d9251":{
      "scriptId":"u40"},
    "d2c1842e82f742c589162f02259f6c7d":{
      "scriptId":"u41"},
    "6212aa04411d4726bbf88225ff2d4d0e":{
      "scriptId":"u42"},
    "605c1f0cfb2a4e0c959f83d031eb55c5":{
      "scriptId":"u43"},
    "480a3806a5ab49928b96b00e31c7fe4c":{
      "scriptId":"u44"},
    "bf5adfe866154ae381df9ab895831758":{
      "scriptId":"u45"},
    "7ef150ecd7b140ca9fbd5085643ded13":{
      "scriptId":"u46"},
    "2e17b8aabc2449bd9f2f36f1b8e44854":{
      "scriptId":"u47"},
    "9126740b1cc64e5dbfe803399afdb729":{
      "scriptId":"u48"},
    "eb78b99102c743188920720ab3b36447":{
      "scriptId":"u49"},
    "7adcaf6ea40c44ca822ccab373751e59":{
      "scriptId":"u50"},
    "6fc588035d3e4d818246e45997f46d62":{
      "scriptId":"u51"},
    "cf5170e5e1e7427cbb9125d3493cff29":{
      "scriptId":"u52"},
    "f35ff69060364fdba084f09c2d62769d":{
      "scriptId":"u53"},
    "a6f2ac60e7b6422ea02a13fe87afd275":{
      "scriptId":"u54"},
    "810503aed3054504bc7a5034ea885d93":{
      "scriptId":"u55"},
    "1c7dac4dedfd4de6a7bef6290ba23c5a":{
      "scriptId":"u56"},
    "5dca9810d966448697a525e31e26efe4":{
      "scriptId":"u57"},
    "4a02fc63c2444250bad5a49ab4a069fb":{
      "scriptId":"u58"},
    "9d1e465849a641af976f5c0f5d58307c":{
      "scriptId":"u59"},
    "137da3f5f6d644a1a5f361fcc8fa9da1":{
      "scriptId":"u60"},
    "bd501547307f4ceb84f891ac2d76b5d5":{
      "scriptId":"u61"},
    "7d93f47c421f47da8ac74362767aae3c":{
      "scriptId":"u62"},
    "a551be0d9a904ec681e53e3c0a134bfb":{
      "scriptId":"u63"},
    "aaae3f0ac1f34230a29428e8736df268":{
      "scriptId":"u64"},
    "71c4482fb4c24732a5c2bd56fcd5d0ed":{
      "scriptId":"u65"},
    "29fcc9fd0b5849ff90bdf90bfd647beb":{
      "scriptId":"u66"},
    "045f1b6bb5ed443083cc084b3833ca8e":{
      "scriptId":"u67"},
    "1b5cc7b31c0c4a4e9db752764f9ef5b1":{
      "scriptId":"u68"},
    "35b8f2973b324c0d9916670bc2a1092e":{
      "scriptId":"u69"},
    "b3aec2141ed7451e97e7d3a4e5b47462":{
      "scriptId":"u70"},
    "d0d07f7929c3449fb0005c9c3da778e7":{
      "scriptId":"u71"},
    "fe638aa8ece44a3eafdd2d3798a900b4":{
      "scriptId":"u72"},
    "b16f01edb37b4ebf9b59ca8f4f3c05cc":{
      "scriptId":"u73"},
    "8ed3c1867f54497887d79e8334f6bfa7":{
      "scriptId":"u74"},
    "c4f743a6e14a4495a7becb65b3cbaf25":{
      "scriptId":"u75"},
    "d7265850dbb6469bb38048c9f6b626dd":{
      "scriptId":"u76"},
    "120f4739ef0945dea0a01fcc9dc44e47":{
      "scriptId":"u77"},
    "d6113df95a7241f28382570ca073dfbd":{
      "scriptId":"u78"},
    "9b4a603dacf24b5986322d415a18483c":{
      "scriptId":"u79"},
    "a6a881c675374f2893372107adfbd53c":{
      "scriptId":"u80"},
    "4fead37990d64e1ab817af96107e28dc":{
      "scriptId":"u81"},
    "693a5a19d57d4316b8448e5f003560ea":{
      "scriptId":"u82"},
    "c092cf041192485b9bedeedac445ccdb":{
      "scriptId":"u83"},
    "79ba1feff7764cc3af412d545afe4a50":{
      "scriptId":"u84"},
    "dc6ddd902e204774a0a59ebe8ec01a29":{
      "scriptId":"u85"},
    "c97f0f057c1248a283774f8eaeac4930":{
      "scriptId":"u86"},
    "4c80444eb8414cde96e2d4376af1bfc4":{
      "scriptId":"u87"},
    "875c2ba3bfa14edeb329c83021e52990":{
      "scriptId":"u88"}}});