$axure.loadCurrentPage({
  "url":"自选盘点列表.html",
  "generationDate":new Date(1479461008189.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"97ab945b9bf1460ca90c4158c741f003",
    "type":"Axure:Page",
    "name":"自选盘点列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ecfa1dcd9da64b5b8996cd3aa28902cc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1025,
              "height":767}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4838735bc15e477680dc62f3e4430807",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1025,
                  "height":767}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自选盘点列表/u0.png"}},
{
          "id":"621dd286549b43e093c08bf21b61228d",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":488,
              "y":700},
            "size":{
              "width":172,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 盘点结果",
                      "target":{
                        "targetType":"page",
                        "url":"盘点结果_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"8860a5c8630a4cae82cb2dbcfd6ed612",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":120},
            "size":{
              "width":850,
              "height":70}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 搜索物料",
                      "target":{
                        "targetType":"page",
                        "url":"搜索物料.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"0b38b5db5e044faab9564feb6a13c7f0",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":190},
            "size":{
              "width":70,
              "height":430}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 输入数量",
                      "target":{
                        "targetType":"page",
                        "url":"输入数量_2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "ecfa1dcd9da64b5b8996cd3aa28902cc":{
      "scriptId":"u0"},
    "4838735bc15e477680dc62f3e4430807":{
      "scriptId":"u1"},
    "621dd286549b43e093c08bf21b61228d":{
      "scriptId":"u2"},
    "8860a5c8630a4cae82cb2dbcfd6ed612":{
      "scriptId":"u3"},
    "0b38b5db5e044faab9564feb6a13c7f0":{
      "scriptId":"u4"}}});