$axure.loadCurrentPage({
  "url":"入库操作.html",
  "generationDate":new Date(1473153213100.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b37f14fdf7684990813a21a266b0d7e8",
    "type":"Axure:Page",
    "name":"入库操作",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e8c898223662435fb3e3f7382fcb08a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":1254,
              "height":890},
            "borderWidth":"2",
            "cornerRadiusTopLeft":"57"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a4bcba9bd8f496b828e67fccef4a156",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":1254,
                  "height":890},
                "borderWidth":"2",
                "cornerRadiusTopLeft":"57"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u0.png"}},
{
          "id":"9f1709f28c364d38979aed836908204d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":115,
              "y":60},
            "size":{
              "width":1024,
              "height":768},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b71de8b2aa44669a6b7db48c7411063",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":115,
                  "y":60},
                "size":{
                  "width":1024,
                  "height":768},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u2.png"}},
{
          "id":"42c95c117bf64abf88ce9081ae9c3c02",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1160,
              "y":410},
            "size":{
              "width":70,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494},
            "cornerRadiusTopLeft":"40"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26161548f71f4ab9bfd067a7bb347219",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1160,
                  "y":410},
                "size":{
                  "width":70,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494},
                "cornerRadiusTopLeft":"40"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u4.png"}},
{
          "id":"dce52efaf66a477d9c37d7e3cb9911b1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":120},
            "size":{
              "width":936,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/查询结果/u10_line.png"}},
{
          "id":"5babcb433b0744d8bc438a8ffe3642c5",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":160},
            "size":{
              "width":936,
              "height":192}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27111825ac334d49bacf6c381f12ddac",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":113,
                  "height":42},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d93132cb6045415fb2204fe6d7517417",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"12px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":113,
                      "height":42},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库操作/u8.png"}},
{
              "id":"8a2d4b4f900d42e2a4c3f7069cb6f7c5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":42},
                "size":{
                  "width":113,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e64845fa79014812aedaf3ee2a739205",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":42},
                    "size":{
                      "width":113,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库操作/u20.png"}},
{
              "id":"cd57b5c7c6054050983cce460f5ea90d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":92},
                "size":{
                  "width":113,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1365e4d6df6444249571cb20aad0a632",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":92},
                    "size":{
                      "width":113,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库操作/u20.png"}},
{
              "id":"94c3d39295144d71a6b2c5f338ab5868",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":113,
                  "y":0},
                "size":{
                  "width":251,
                  "height":42},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bd7cf2f6ebab40fbb1e052635fa0d255",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"12px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":113,
                      "y":0},
                    "size":{
                      "width":251,
                      "height":42},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库操作/u10.png"}},
{
              "id":"d26772204a044ea980ef7ebd532b1319",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":113,
                  "y":42},
                "size":{
                  "width":251,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"109f13dee651488db7fe1fd45245a201",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":113,
                      "y":42},
                    "size":{
                      "width":251,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库操作/u22.png"}},
{
              "id":"ca984574534f4f0b8d613f08eba08cf4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":113,
                  "y":92},
                "size":{
                  "width":251,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2678666a56344ce89be6bf870efe03bd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":113,
                      "y":92},
                    "size":{
                      "width":251,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库操作/u22.png"}},
{
              "id":"518e8e6a76bf4480be0e7604afbc2c28",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":142},
                "size":{
                  "width":113,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eabb5416277b41d7beecf137559a04b5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":142},
                    "size":{
                      "width":113,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库操作/u20.png"}},
{
              "id":"88bad5c0202f4b649b523affb2e2a0bc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":113,
                  "y":142},
                "size":{
                  "width":251,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cad6747f4f584a77b7c4bb680c21e7c3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":113,
                      "y":142},
                    "size":{
                      "width":251,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库操作/u22.png"}},
{
              "id":"fc9c03dedeef44fdaa0ac331f889ea8a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":364,
                  "y":0},
                "size":{
                  "width":123,
                  "height":42},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"541b711bfbe04aaaa911f33cd82c672f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"12px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":364,
                      "y":0},
                    "size":{
                      "width":123,
                      "height":42},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库操作/u12.png"}},
{
              "id":"72007fe3a06e487e9109e67f991f6030",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":364,
                  "y":42},
                "size":{
                  "width":123,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3d07722181634c77a13c6c64c39eff92",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":364,
                      "y":42},
                    "size":{
                      "width":123,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库操作/u24.png"}},
{
              "id":"8839fcb1ef4a415eb44fb5ed9b7c5d34",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":364,
                  "y":92},
                "size":{
                  "width":123,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"949b111bfed34412b18192b64d594823",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":364,
                      "y":92},
                    "size":{
                      "width":123,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库操作/u24.png"}},
{
              "id":"ec9819ccfc654d09b529a572b62ab812",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":364,
                  "y":142},
                "size":{
                  "width":123,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0488bbcedc544789bfe26dad713c3d88",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":364,
                      "y":142},
                    "size":{
                      "width":123,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库操作/u24.png"}},
{
              "id":"21a229e39e74437f86ec2d09dcb8cac2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":643,
                  "y":0},
                "size":{
                  "width":138,
                  "height":42},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ec28a708bf924eafb361614228a0c605",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"12px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":643,
                      "y":0},
                    "size":{
                      "width":138,
                      "height":42},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库操作/u16.png"}},
{
              "id":"cd1fadf28ba94574a673851d61e181a5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":643,
                  "y":42},
                "size":{
                  "width":138,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7efa03fbb699454cb3671c6602aa6ed2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":643,
                      "y":42},
                    "size":{
                      "width":138,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库操作/u28.png"}},
{
              "id":"96f17ba7aa7148b987fbe4560dab2844",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":643,
                  "y":92},
                "size":{
                  "width":138,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"34e014166964410daa32889d79095b63",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":643,
                      "y":92},
                    "size":{
                      "width":138,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库操作/u28.png"}},
{
              "id":"a0f52cc6c74749229fc2b38d1e537999",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":643,
                  "y":142},
                "size":{
                  "width":138,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f33c5109d1dc429c999de454149fc8f2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":643,
                      "y":142},
                    "size":{
                      "width":138,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库操作/u28.png"}},
{
              "id":"d6e542a9e6b44bafa5b3a51f45fe5e35",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":487,
                  "y":0},
                "size":{
                  "width":156,
                  "height":42},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b949e8c5146c499da437784cb49c889b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"12px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":487,
                      "y":0},
                    "size":{
                      "width":156,
                      "height":42},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/紧急订货/u20.png"}},
{
              "id":"f1cc5e9040cd4079a31c8f84dff96d2d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":487,
                  "y":42},
                "size":{
                  "width":156,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"973b864d35fa4f1b8766742e2cec4253",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":487,
                      "y":42},
                    "size":{
                      "width":156,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/紧急订货/u32.png"}},
{
              "id":"9417fe2a77bf4c0abc9a5d61b1c17a8a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":487,
                  "y":92},
                "size":{
                  "width":156,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3dd5e716a1244f3c9a3f06664f631326",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":487,
                      "y":92},
                    "size":{
                      "width":156,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/紧急订货/u32.png"}},
{
              "id":"58d35e83858f46baabc863c52e6f18d3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":487,
                  "y":142},
                "size":{
                  "width":156,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ee2898bf6f8f4efcbbd3a2be146cf739",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":487,
                      "y":142},
                    "size":{
                      "width":156,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/紧急订货/u32.png"}},
{
              "id":"2b01a8b22f534f8a9bd6e54155061598",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":781,
                  "y":0},
                "size":{
                  "width":155,
                  "height":42},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"559de320bb1f4da9831f4ade92839dcb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"12px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":781,
                      "y":0},
                    "size":{
                      "width":155,
                      "height":42},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库操作/u18.png"}},
{
              "id":"907c5abc4d334da39f47a7fee613d825",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":781,
                  "y":42},
                "size":{
                  "width":155,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"58a50ea5140d457280a807f57e8cbb81",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":781,
                      "y":42},
                    "size":{
                      "width":155,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库操作/u30.png"}},
{
              "id":"902b728df3574149a15d2991a3294d3d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":781,
                  "y":92},
                "size":{
                  "width":155,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a06f2f94ac844584bc3304630206f6cf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"12px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":781,
                      "y":92},
                    "size":{
                      "width":155,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库操作/u30.png"}},
{
              "id":"e0304bd6e88e44b48e14eea228c60693",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":781,
                  "y":142},
                "size":{
                  "width":155,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fdff475890e646098c819e00bf62e395",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"12px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":781,
                      "y":142},
                    "size":{
                      "width":155,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库操作/u30.png"}}]},
{
          "id":"e078dd6897e94bc29431945928bebbaf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":168,
              "y":88},
            "size":{
              "width":146,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d475bcff554348e994e59520da569255",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":168,
                  "y":88},
                "size":{
                  "width":146,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9422939abd364ca9a5bada6b00aece67",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":610.5,
              "y":745},
            "size":{
              "width":160,
              "height":35},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a065755978594d53aac011969b17ee61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":610.5,
                  "y":745},
                "size":{
                  "width":160,
                  "height":35},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/库存预警/u7.png"}},
{
          "id":"55765ac89bed457499196495bcf03d00",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":244},
            "size":{
              "width":936,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/查询结果/u52_line.png"}},
{
          "id":"06420fd23b864d898a0a5038b6146612",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":293},
            "size":{
              "width":936,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/查询结果/u52_line.png"}},
{
          "id":"122a6025443f40cfa7fb90095966c646",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":344},
            "size":{
              "width":936,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/查询结果/u52_line.png"}},
{
          "id":"dd29e7d6f4b445268adf6de53615a3ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":483.5,
              "y":748},
            "size":{
              "width":100,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c73131bb11194b13a6e8267ec14f97aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":483.5,
                  "y":748},
                "size":{
                  "width":100,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/紧急订货/u63.png"}},
{
          "id":"f79435c141dc4e7cb62bef76665da3c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":960},
            "size":{
              "width":500,
              "height":300},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"442f5a83c7aa49ca92fe4a023417ce5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":960},
                "size":{
                  "width":500,
                  "height":300},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/紧急订货/u66.png"}},
{
          "id":"5cf9e349f5164a0da1349e0c3b1d0d8f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":1015},
            "size":{
              "width":500,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/紧急订货/u68_line.png"}},
{
          "id":"808ce8dff30b47138390652a19eb36fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":674,
              "y":981},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3e3bb9350a04a66af276c5994d9cde8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":674,
                  "y":981},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc9c8d073ec14c9fa1e7826c821ad5fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":546,
              "y":1084},
            "size":{
              "width":287,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28923c35810b4fa99244934162bd085c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":546,
                  "y":1084},
                "size":{
                  "width":287,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf6f8fa8bb434c56bc8ffe8d725e4184",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":628.5,
              "y":1185},
            "size":{
              "width":123,
              "height":35},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27ce2d77e639440e8b60f2c6ec7086de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":628.5,
                  "y":1185},
                "size":{
                  "width":123,
                  "height":35},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/紧急订货/u71.png"}},
{
          "id":"77e8904fc3e4405d9bea106aa666c074",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":685,
              "y":790},
            "size":{
              "width":10,
              "height":160},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/紧急订货/u65_end.png",
            "line~":"images/紧急订货/u65_line.png"}},
{
          "id":"a1c1672736a842578db30ae527f975d0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":878.5,
              "y":219},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98c28cfa8bea4b6caa9c1573c09ea5ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":878.5,
                  "y":219},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入库操作/u75.png"}},
{
          "id":"feb848d1b01c4bc49ff578d64e86ebff",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":876,
              "y":266},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdc234b045d74b04b0783594ca07d6c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":876,
                  "y":266},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/紧急订货/u79.png"}},
{
          "id":"f66069522df347908a6858672f13c46a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":825,
              "y":309},
            "size":{
              "width":74,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc05cdd74e1f4fc4b7d54f57a2065b73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":825,
                  "y":309},
                "size":{
                  "width":74,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/紧急订货/u83.png"}},
{
          "id":"7ab6033455fa403686560afb57733d97",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":903,
              "y":974},
            "size":{
              "width":17,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db18f38b5b1d447d94364c54f45e0d11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":903,
                  "y":974},
                "size":{
                  "width":17,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1130f62d6b2c4f09a5ead93092ad4051",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":330},
            "size":{
              "width":10,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/紧急订货/u65_end.png",
            "line~":"images/入库操作/u83_line.png"}},
{
          "id":"8fad148f6f564af2987c64ce52fdaae5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":825,
              "y":410},
            "size":{
              "width":183,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d21e2e68a4a2405482896fce6fd3b557",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":825,
                  "y":410},
                "size":{
                  "width":183,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a81d9f5a2a7944128313b777eaf6c928",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":903,
              "y":219},
            "size":{
              "width":407,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/紧急订货/u87_end.png",
            "line~":"images/入库操作/u86_line.png"}},
{
          "id":"3b8541fd5f844af6b0c86ee7a82a5b89",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":1320,
              "y":213},
            "size":{
              "width":170,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8dda957680649cfbc0fa45d93f72ddf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":1320,
                  "y":213},
                "size":{
                  "width":170,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e8c898223662435fb3e3f7382fcb08a4":{
      "scriptId":"u0"},
    "1a4bcba9bd8f496b828e67fccef4a156":{
      "scriptId":"u1"},
    "9f1709f28c364d38979aed836908204d":{
      "scriptId":"u2"},
    "5b71de8b2aa44669a6b7db48c7411063":{
      "scriptId":"u3"},
    "42c95c117bf64abf88ce9081ae9c3c02":{
      "scriptId":"u4"},
    "26161548f71f4ab9bfd067a7bb347219":{
      "scriptId":"u5"},
    "dce52efaf66a477d9c37d7e3cb9911b1":{
      "scriptId":"u6"},
    "5babcb433b0744d8bc438a8ffe3642c5":{
      "scriptId":"u7"},
    "27111825ac334d49bacf6c381f12ddac":{
      "scriptId":"u8"},
    "d93132cb6045415fb2204fe6d7517417":{
      "scriptId":"u9"},
    "94c3d39295144d71a6b2c5f338ab5868":{
      "scriptId":"u10"},
    "bd7cf2f6ebab40fbb1e052635fa0d255":{
      "scriptId":"u11"},
    "fc9c03dedeef44fdaa0ac331f889ea8a":{
      "scriptId":"u12"},
    "541b711bfbe04aaaa911f33cd82c672f":{
      "scriptId":"u13"},
    "d6e542a9e6b44bafa5b3a51f45fe5e35":{
      "scriptId":"u14"},
    "b949e8c5146c499da437784cb49c889b":{
      "scriptId":"u15"},
    "21a229e39e74437f86ec2d09dcb8cac2":{
      "scriptId":"u16"},
    "ec28a708bf924eafb361614228a0c605":{
      "scriptId":"u17"},
    "2b01a8b22f534f8a9bd6e54155061598":{
      "scriptId":"u18"},
    "559de320bb1f4da9831f4ade92839dcb":{
      "scriptId":"u19"},
    "8a2d4b4f900d42e2a4c3f7069cb6f7c5":{
      "scriptId":"u20"},
    "e64845fa79014812aedaf3ee2a739205":{
      "scriptId":"u21"},
    "d26772204a044ea980ef7ebd532b1319":{
      "scriptId":"u22"},
    "109f13dee651488db7fe1fd45245a201":{
      "scriptId":"u23"},
    "72007fe3a06e487e9109e67f991f6030":{
      "scriptId":"u24"},
    "3d07722181634c77a13c6c64c39eff92":{
      "scriptId":"u25"},
    "f1cc5e9040cd4079a31c8f84dff96d2d":{
      "scriptId":"u26"},
    "973b864d35fa4f1b8766742e2cec4253":{
      "scriptId":"u27"},
    "cd1fadf28ba94574a673851d61e181a5":{
      "scriptId":"u28"},
    "7efa03fbb699454cb3671c6602aa6ed2":{
      "scriptId":"u29"},
    "907c5abc4d334da39f47a7fee613d825":{
      "scriptId":"u30"},
    "58a50ea5140d457280a807f57e8cbb81":{
      "scriptId":"u31"},
    "cd57b5c7c6054050983cce460f5ea90d":{
      "scriptId":"u32"},
    "1365e4d6df6444249571cb20aad0a632":{
      "scriptId":"u33"},
    "ca984574534f4f0b8d613f08eba08cf4":{
      "scriptId":"u34"},
    "2678666a56344ce89be6bf870efe03bd":{
      "scriptId":"u35"},
    "8839fcb1ef4a415eb44fb5ed9b7c5d34":{
      "scriptId":"u36"},
    "949b111bfed34412b18192b64d594823":{
      "scriptId":"u37"},
    "9417fe2a77bf4c0abc9a5d61b1c17a8a":{
      "scriptId":"u38"},
    "3dd5e716a1244f3c9a3f06664f631326":{
      "scriptId":"u39"},
    "96f17ba7aa7148b987fbe4560dab2844":{
      "scriptId":"u40"},
    "34e014166964410daa32889d79095b63":{
      "scriptId":"u41"},
    "902b728df3574149a15d2991a3294d3d":{
      "scriptId":"u42"},
    "a06f2f94ac844584bc3304630206f6cf":{
      "scriptId":"u43"},
    "518e8e6a76bf4480be0e7604afbc2c28":{
      "scriptId":"u44"},
    "eabb5416277b41d7beecf137559a04b5":{
      "scriptId":"u45"},
    "88bad5c0202f4b649b523affb2e2a0bc":{
      "scriptId":"u46"},
    "cad6747f4f584a77b7c4bb680c21e7c3":{
      "scriptId":"u47"},
    "ec9819ccfc654d09b529a572b62ab812":{
      "scriptId":"u48"},
    "0488bbcedc544789bfe26dad713c3d88":{
      "scriptId":"u49"},
    "58d35e83858f46baabc863c52e6f18d3":{
      "scriptId":"u50"},
    "ee2898bf6f8f4efcbbd3a2be146cf739":{
      "scriptId":"u51"},
    "a0f52cc6c74749229fc2b38d1e537999":{
      "scriptId":"u52"},
    "f33c5109d1dc429c999de454149fc8f2":{
      "scriptId":"u53"},
    "e0304bd6e88e44b48e14eea228c60693":{
      "scriptId":"u54"},
    "fdff475890e646098c819e00bf62e395":{
      "scriptId":"u55"},
    "e078dd6897e94bc29431945928bebbaf":{
      "scriptId":"u56"},
    "d475bcff554348e994e59520da569255":{
      "scriptId":"u57"},
    "9422939abd364ca9a5bada6b00aece67":{
      "scriptId":"u58"},
    "a065755978594d53aac011969b17ee61":{
      "scriptId":"u59"},
    "55765ac89bed457499196495bcf03d00":{
      "scriptId":"u60"},
    "06420fd23b864d898a0a5038b6146612":{
      "scriptId":"u61"},
    "122a6025443f40cfa7fb90095966c646":{
      "scriptId":"u62"},
    "dd29e7d6f4b445268adf6de53615a3ee":{
      "scriptId":"u63"},
    "c73131bb11194b13a6e8267ec14f97aa":{
      "scriptId":"u64"},
    "f79435c141dc4e7cb62bef76665da3c9":{
      "scriptId":"u65"},
    "442f5a83c7aa49ca92fe4a023417ce5f":{
      "scriptId":"u66"},
    "5cf9e349f5164a0da1349e0c3b1d0d8f":{
      "scriptId":"u67"},
    "808ce8dff30b47138390652a19eb36fe":{
      "scriptId":"u68"},
    "d3e3bb9350a04a66af276c5994d9cde8":{
      "scriptId":"u69"},
    "bc9c8d073ec14c9fa1e7826c821ad5fe":{
      "scriptId":"u70"},
    "28923c35810b4fa99244934162bd085c":{
      "scriptId":"u71"},
    "bf6f8fa8bb434c56bc8ffe8d725e4184":{
      "scriptId":"u72"},
    "27ce2d77e639440e8b60f2c6ec7086de":{
      "scriptId":"u73"},
    "77e8904fc3e4405d9bea106aa666c074":{
      "scriptId":"u74"},
    "a1c1672736a842578db30ae527f975d0":{
      "scriptId":"u75"},
    "98c28cfa8bea4b6caa9c1573c09ea5ca":{
      "scriptId":"u76"},
    "feb848d1b01c4bc49ff578d64e86ebff":{
      "scriptId":"u77"},
    "cdc234b045d74b04b0783594ca07d6c3":{
      "scriptId":"u78"},
    "f66069522df347908a6858672f13c46a":{
      "scriptId":"u79"},
    "dc05cdd74e1f4fc4b7d54f57a2065b73":{
      "scriptId":"u80"},
    "7ab6033455fa403686560afb57733d97":{
      "scriptId":"u81"},
    "db18f38b5b1d447d94364c54f45e0d11":{
      "scriptId":"u82"},
    "1130f62d6b2c4f09a5ead93092ad4051":{
      "scriptId":"u83"},
    "8fad148f6f564af2987c64ce52fdaae5":{
      "scriptId":"u84"},
    "d21e2e68a4a2405482896fce6fd3b557":{
      "scriptId":"u85"},
    "a81d9f5a2a7944128313b777eaf6c928":{
      "scriptId":"u86"},
    "3b8541fd5f844af6b0c86ee7a82a5b89":{
      "scriptId":"u87"},
    "e8dda957680649cfbc0fa45d93f72ddf":{
      "scriptId":"u88"}}});