$axure.loadCurrentPage({
  "url":"建立库存.html",
  "generationDate":new Date(1473153215877.18),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0d68561f0af64e04a3a287ec4d889b41",
    "type":"Axure:Page",
    "name":"建立库存",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c9fa68f4e7f747899b4c8d125b430289",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":0,
              "y":1080},
            "size":{
              "width":1254,
              "height":890},
            "borderWidth":"2",
            "cornerRadiusTopLeft":"57"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"104f4de8f90f4774a4211cd2f2553c63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":1080},
                "size":{
                  "width":1254,
                  "height":890},
                "borderWidth":"2",
                "cornerRadiusTopLeft":"57"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u0.png"}},
{
          "id":"fefc5b4ad9dd4b6f812a2ba51c75816b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":115,
              "y":1140},
            "size":{
              "width":1024,
              "height":768},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39c09aa2112b4cda84ad7f1c9792ba60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":115,
                  "y":1140},
                "size":{
                  "width":1024,
                  "height":768},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u2.png"}},
{
          "id":"0144e017a411475cb2bad7be3000f574",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1160,
              "y":1490},
            "size":{
              "width":70,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494},
            "cornerRadiusTopLeft":"40"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50d181fed3b74b739710ab77303b9506",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1160,
                  "y":1490},
                "size":{
                  "width":70,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494},
                "cornerRadiusTopLeft":"40"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u4.png"}},
{
          "id":"9fcdd0a07e724c108238e79d9c077351",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":1231},
            "size":{
              "width":936,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/查询结果/u10_line.png"}},
{
          "id":"15d494d2fc8341f6972d25b5a4472165",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":159,
              "y":1188},
            "size":{
              "width":85,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74c21f5d39e641b4ab467df3cdb4b533",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":159,
                  "y":1188},
                "size":{
                  "width":85,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5248c6e0be4d4e408bb13aebdeb37a58",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":1262},
            "size":{
              "width":936,
              "height":192}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1b3f61cf09a43f787640e7bdd856caf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":134,
                  "height":42},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eeec00132f644ebc9f14eeeee7269996",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"12px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":134,
                      "height":42},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/动碰_全盘/u10.png"}},
{
              "id":"96d9728fbd104ff980501cc102a63dbf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":42},
                "size":{
                  "width":134,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"77fd75dbfd7c4877ba2fa3decfa7b6f6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":42},
                    "size":{
                      "width":134,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/动碰_全盘/u18.png"}},
{
              "id":"2cb2bc5229db40f49b0a6fc65ac4b891",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":92},
                "size":{
                  "width":134,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"862cd835082143c3863e3134e9d0635a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":92},
                    "size":{
                      "width":134,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/动碰_全盘/u18.png"}},
{
              "id":"0d878fab0b424bcc940b9be751a01cc5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":134,
                  "y":0},
                "size":{
                  "width":308,
                  "height":42},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1481759df6fe48a79fc929e0f59d2e6f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"12px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":134,
                      "y":0},
                    "size":{
                      "width":308,
                      "height":42},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/动碰_全盘/u12.png"}},
{
              "id":"efa1dd197a144a8585f459c9b6bdfb7b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":134,
                  "y":42},
                "size":{
                  "width":308,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3540417ad89347ba800f99125ed18599",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":134,
                      "y":42},
                    "size":{
                      "width":308,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/动碰_全盘/u20.png"}},
{
              "id":"df6f0954ac64429398adde108a2c7acc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":134,
                  "y":92},
                "size":{
                  "width":308,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c575a389b58f4b8d9d9d7941c0911a8a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":134,
                      "y":92},
                    "size":{
                      "width":308,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/动碰_全盘/u20.png"}},
{
              "id":"010ba636c2c8425bb8a73f241285df9e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":142},
                "size":{
                  "width":134,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"df1adff2c92a4a55bc4ae6e9b5d4a391",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":142},
                    "size":{
                      "width":134,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/动碰_全盘/u18.png"}},
{
              "id":"cd4a79d47dce4b50b24f25c7738b0cc2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":134,
                  "y":142},
                "size":{
                  "width":308,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"61dd41c21ef04b53ade9971d71dd704b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":134,
                      "y":142},
                    "size":{
                      "width":308,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/动碰_全盘/u20.png"}},
{
              "id":"93a3d7021a8f458e962d5f67c0c12d6c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":442,
                  "y":0},
                "size":{
                  "width":259,
                  "height":42},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"85f9c886afaf452eaa2ad2fa56750a89",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"12px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":442,
                      "y":0},
                    "size":{
                      "width":259,
                      "height":42},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点/u24.png"}},
{
              "id":"b330b186ed6e49389fb97c2c0c70eff2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":442,
                  "y":42},
                "size":{
                  "width":259,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"912ac574349c400bbcf153ae59c7449f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":442,
                      "y":42},
                    "size":{
                      "width":259,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点/u32.png"}},
{
              "id":"d881a683d3554fda93536adf5ee7e4e4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":442,
                  "y":92},
                "size":{
                  "width":259,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e65f16c20fc34390a7cd3d6435a0bf5f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":442,
                      "y":92},
                    "size":{
                      "width":259,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点/u32.png"}},
{
              "id":"23b09c75e3f9442ca1b22839ce906fc4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":442,
                  "y":142},
                "size":{
                  "width":259,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9594aafc3c39431f9a306bc9a45c2dca",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":442,
                      "y":142},
                    "size":{
                      "width":259,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点/u32.png"}},
{
              "id":"24d314bb724546e98b03608dbd216752",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":701,
                  "y":0},
                "size":{
                  "width":235,
                  "height":42},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3a41c4d7046a4201b32e952975cc2487",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"12px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":701,
                      "y":0},
                    "size":{
                      "width":235,
                      "height":42},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点/u26.png"}},
{
              "id":"ccd3b7ce158245bc889065a5a63c7740",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":701,
                  "y":42},
                "size":{
                  "width":235,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d9d99ac71503486599dcefb3ebc262ab",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":701,
                      "y":42},
                    "size":{
                      "width":235,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点/u34.png"}},
{
              "id":"03d88365b018459db42461af6b6dd6a5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":701,
                  "y":92},
                "size":{
                  "width":235,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"048b31e94966450eae727a69e5b3c623",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":701,
                      "y":92},
                    "size":{
                      "width":235,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点/u34.png"}},
{
              "id":"624034adb4304f0db3d31079312ae180",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":701,
                  "y":142},
                "size":{
                  "width":235,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bc99ae51519242df8d37eaa85f17314b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":701,
                      "y":142},
                    "size":{
                      "width":235,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点/u34.png"}}]},
{
          "id":"b8cedddf6cdc40fb892b75653cfd753a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":1346},
            "size":{
              "width":936,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/查询结果/u52_line.png"}},
{
          "id":"23dc78fc0c584fd08eeeb6a55acf86b3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":1395},
            "size":{
              "width":936,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/查询结果/u52_line.png"}},
{
          "id":"d23d0d2f2e9a49db9e3b27141ce178d7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":1446},
            "size":{
              "width":936,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/查询结果/u52_line.png"}},
{
          "id":"39c04669facd48ed9b935a74d70b00c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":547,
              "y":1841},
            "size":{
              "width":160,
              "height":35},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"665da9114c4340a2acc061f995eaba07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":547,
                  "y":1841},
                "size":{
                  "width":160,
                  "height":35},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/库存预警/u7.png"}},
{
          "id":"70055f5cc1184be9b728a7253ed852b0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":921,
              "y":1317},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d77ef39fea694541959c7c10cce5bdfe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":921,
                  "y":1317},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/紧急订货/u79.png"}},
{
          "id":"6436a7a439234055bcb2bdd3266742fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":1412},
            "size":{
              "width":74,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c17429df764428380ca732df2be3258",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":870,
                  "y":1412},
                "size":{
                  "width":74,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/紧急订货/u83.png"}},
{
          "id":"be97a34c38a4451f9525b11e55f3e9e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":1254,
              "height":890},
            "borderWidth":"2",
            "cornerRadiusTopLeft":"57"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a46b0ade4a19411c9edee35fa4d58a81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":1254,
                  "height":890},
                "borderWidth":"2",
                "cornerRadiusTopLeft":"57"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u0.png"}},
{
          "id":"d763b9ca9294437b8e84c15ce1c0a567",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":115,
              "y":60},
            "size":{
              "width":1024,
              "height":768},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b2a292a36a448fc8dea66379ff963fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":115,
                  "y":60},
                "size":{
                  "width":1024,
                  "height":768},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u2.png"}},
{
          "id":"508f675896844010b809c08601068b6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1160,
              "y":410},
            "size":{
              "width":70,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494},
            "cornerRadiusTopLeft":"40"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6f7254930a74aa18662d1ce08c0822e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1160,
                  "y":410},
                "size":{
                  "width":70,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494},
                "cornerRadiusTopLeft":"40"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u4.png"}},
{
          "id":"93c254123152481eb056203758db426c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":143,
              "y":161},
            "size":{
              "width":936,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/查询结果/u10_line.png"}},
{
          "id":"0fae1c6080684435a0aa041187660217",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":143,
              "y":118},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b7a56088659434daf149bb9e504d8f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":143,
                  "y":118},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"73c2a7512a3b4d8ab0ea4ee4818d4d19",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":361,
              "y":240},
            "size":{
              "width":500,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0492af9cd7214b10b06ce2393ec8466f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":361,
                  "y":240},
                "size":{
                  "width":500,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u6.png"}},
{
          "id":"8f4b368afbfc4b95b9bb95107d9bc258",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":255},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cc3046579cb4a20988150c08fc1bca1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":840,
                  "y":255},
                "size":{
                  "width":10,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/紧急订货/u75.png"}},
{
          "id":"17eef76bb48649c5a601cb9be2461d38",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":371,
              "y":252},
            "size":{
              "width":79,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8985b39b2222452c8c8ab647ff03b722",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":371,
                  "y":252},
                "size":{
                  "width":79,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5cfabfb77d994e4f874f647db2ea8bc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":531,
              "y":745},
            "size":{
              "width":160,
              "height":35},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82577cb953b0425e93485368181f5708",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":531,
                  "y":745},
                "size":{
                  "width":160,
                  "height":35},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/库存预警/u7.png"}},
{
          "id":"06a831871ebb4c44afb7cb8d370a9b3d",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":800},
            "size":{
              "width":10,
              "height":250},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/紧急订货/u65_end.png",
            "line~":"images/建立库存/u68_line.png"}},
{
          "id":"2a7eb1520484431e809232d18ac17a96",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":879,
              "y":258},
            "size":{
              "width":421,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/紧急订货/u87_end.png",
            "line~":"images/抽样盘点/u23_line.png"}},
{
          "id":"7702c858203a4d58ba7a0849b3e555c2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1310,
              "y":252},
            "size":{
              "width":533,
              "height":147}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"080e86fa87c04b8688fd79ba03a95372",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1310,
                  "y":252},
                "size":{
                  "width":533,
                  "height":147}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/抽样盘点/u24.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c9fa68f4e7f747899b4c8d125b430289":{
      "scriptId":"u0"},
    "104f4de8f90f4774a4211cd2f2553c63":{
      "scriptId":"u1"},
    "fefc5b4ad9dd4b6f812a2ba51c75816b":{
      "scriptId":"u2"},
    "39c09aa2112b4cda84ad7f1c9792ba60":{
      "scriptId":"u3"},
    "0144e017a411475cb2bad7be3000f574":{
      "scriptId":"u4"},
    "50d181fed3b74b739710ab77303b9506":{
      "scriptId":"u5"},
    "9fcdd0a07e724c108238e79d9c077351":{
      "scriptId":"u6"},
    "15d494d2fc8341f6972d25b5a4472165":{
      "scriptId":"u7"},
    "74c21f5d39e641b4ab467df3cdb4b533":{
      "scriptId":"u8"},
    "5248c6e0be4d4e408bb13aebdeb37a58":{
      "scriptId":"u9"},
    "d1b3f61cf09a43f787640e7bdd856caf":{
      "scriptId":"u10"},
    "eeec00132f644ebc9f14eeeee7269996":{
      "scriptId":"u11"},
    "0d878fab0b424bcc940b9be751a01cc5":{
      "scriptId":"u12"},
    "1481759df6fe48a79fc929e0f59d2e6f":{
      "scriptId":"u13"},
    "93a3d7021a8f458e962d5f67c0c12d6c":{
      "scriptId":"u14"},
    "85f9c886afaf452eaa2ad2fa56750a89":{
      "scriptId":"u15"},
    "24d314bb724546e98b03608dbd216752":{
      "scriptId":"u16"},
    "3a41c4d7046a4201b32e952975cc2487":{
      "scriptId":"u17"},
    "96d9728fbd104ff980501cc102a63dbf":{
      "scriptId":"u18"},
    "77fd75dbfd7c4877ba2fa3decfa7b6f6":{
      "scriptId":"u19"},
    "efa1dd197a144a8585f459c9b6bdfb7b":{
      "scriptId":"u20"},
    "3540417ad89347ba800f99125ed18599":{
      "scriptId":"u21"},
    "b330b186ed6e49389fb97c2c0c70eff2":{
      "scriptId":"u22"},
    "912ac574349c400bbcf153ae59c7449f":{
      "scriptId":"u23"},
    "ccd3b7ce158245bc889065a5a63c7740":{
      "scriptId":"u24"},
    "d9d99ac71503486599dcefb3ebc262ab":{
      "scriptId":"u25"},
    "2cb2bc5229db40f49b0a6fc65ac4b891":{
      "scriptId":"u26"},
    "862cd835082143c3863e3134e9d0635a":{
      "scriptId":"u27"},
    "df6f0954ac64429398adde108a2c7acc":{
      "scriptId":"u28"},
    "c575a389b58f4b8d9d9d7941c0911a8a":{
      "scriptId":"u29"},
    "d881a683d3554fda93536adf5ee7e4e4":{
      "scriptId":"u30"},
    "e65f16c20fc34390a7cd3d6435a0bf5f":{
      "scriptId":"u31"},
    "03d88365b018459db42461af6b6dd6a5":{
      "scriptId":"u32"},
    "048b31e94966450eae727a69e5b3c623":{
      "scriptId":"u33"},
    "010ba636c2c8425bb8a73f241285df9e":{
      "scriptId":"u34"},
    "df1adff2c92a4a55bc4ae6e9b5d4a391":{
      "scriptId":"u35"},
    "cd4a79d47dce4b50b24f25c7738b0cc2":{
      "scriptId":"u36"},
    "61dd41c21ef04b53ade9971d71dd704b":{
      "scriptId":"u37"},
    "23b09c75e3f9442ca1b22839ce906fc4":{
      "scriptId":"u38"},
    "9594aafc3c39431f9a306bc9a45c2dca":{
      "scriptId":"u39"},
    "624034adb4304f0db3d31079312ae180":{
      "scriptId":"u40"},
    "bc99ae51519242df8d37eaa85f17314b":{
      "scriptId":"u41"},
    "b8cedddf6cdc40fb892b75653cfd753a":{
      "scriptId":"u42"},
    "23dc78fc0c584fd08eeeb6a55acf86b3":{
      "scriptId":"u43"},
    "d23d0d2f2e9a49db9e3b27141ce178d7":{
      "scriptId":"u44"},
    "39c04669facd48ed9b935a74d70b00c4":{
      "scriptId":"u45"},
    "665da9114c4340a2acc061f995eaba07":{
      "scriptId":"u46"},
    "70055f5cc1184be9b728a7253ed852b0":{
      "scriptId":"u47"},
    "d77ef39fea694541959c7c10cce5bdfe":{
      "scriptId":"u48"},
    "6436a7a439234055bcb2bdd3266742fe":{
      "scriptId":"u49"},
    "8c17429df764428380ca732df2be3258":{
      "scriptId":"u50"},
    "be97a34c38a4451f9525b11e55f3e9e0":{
      "scriptId":"u51"},
    "a46b0ade4a19411c9edee35fa4d58a81":{
      "scriptId":"u52"},
    "d763b9ca9294437b8e84c15ce1c0a567":{
      "scriptId":"u53"},
    "2b2a292a36a448fc8dea66379ff963fc":{
      "scriptId":"u54"},
    "508f675896844010b809c08601068b6c":{
      "scriptId":"u55"},
    "b6f7254930a74aa18662d1ce08c0822e":{
      "scriptId":"u56"},
    "93c254123152481eb056203758db426c":{
      "scriptId":"u57"},
    "0fae1c6080684435a0aa041187660217":{
      "scriptId":"u58"},
    "0b7a56088659434daf149bb9e504d8f4":{
      "scriptId":"u59"},
    "73c2a7512a3b4d8ab0ea4ee4818d4d19":{
      "scriptId":"u60"},
    "0492af9cd7214b10b06ce2393ec8466f":{
      "scriptId":"u61"},
    "8f4b368afbfc4b95b9bb95107d9bc258":{
      "scriptId":"u62"},
    "0cc3046579cb4a20988150c08fc1bca1":{
      "scriptId":"u63"},
    "17eef76bb48649c5a601cb9be2461d38":{
      "scriptId":"u64"},
    "8985b39b2222452c8c8ab647ff03b722":{
      "scriptId":"u65"},
    "5cfabfb77d994e4f874f647db2ea8bc8":{
      "scriptId":"u66"},
    "82577cb953b0425e93485368181f5708":{
      "scriptId":"u67"},
    "06a831871ebb4c44afb7cb8d370a9b3d":{
      "scriptId":"u68"},
    "2a7eb1520484431e809232d18ac17a96":{
      "scriptId":"u69"},
    "7702c858203a4d58ba7a0849b3e555c2":{
      "scriptId":"u70"},
    "080e86fa87c04b8688fd79ba03a95372":{
      "scriptId":"u71"}}});