$axure.loadCurrentPage({
  "url":"更多员工.html",
  "generationDate":new Date(1482148484477.34),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cbe16f58fd9c4cd0bcb02d657b47ebed",
    "type":"Axure:Page",
    "name":"更多员工",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"95d1ed3c60e24c52b92c892c635ccf04",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1024,
              "height":768}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"718f19076b83456684779f4e9fed7845",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1024,
                  "height":768}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更多员工/u0.png"}},
{
          "id":"3531dfa536924cf58c7298a1c6f903f1",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":320},
            "size":{
              "width":430,
              "height":130}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 物料",
                      "target":{
                        "targetType":"page",
                        "url":"物料.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "95d1ed3c60e24c52b92c892c635ccf04":{
      "scriptId":"u0"},
    "718f19076b83456684779f4e9fed7845":{
      "scriptId":"u1"},
    "3531dfa536924cf58c7298a1c6f903f1":{
      "scriptId":"u2"}}});