$axure.loadCurrentPage({
  "url":"入库首页.html",
  "generationDate":new Date(1479461008317.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8dd23f8fd60240fc824ccc9363a5dade",
    "type":"Axure:Page",
    "name":"入库首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"18a28b66daf9469fa17b3e6f39bd488c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1023,
              "height":768}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03bc1bec72924f5f8253f2de9f16e304",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1023,
                  "height":768}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入库首页/u0.png"}},
{
          "id":"ec597a011b74445db7dcaed7323fc30e",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":359},
            "size":{
              "width":290,
              "height":211}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 拒单详情",
                      "target":{
                        "targetType":"page",
                        "url":"拒单详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"10694471815e47bea9a96bb41dc5051b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":477,
              "y":82},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 待入库",
                      "target":{
                        "targetType":"page",
                        "url":"待入库.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"73ffa81779954a218230de9bb323e74d",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":677,
              "y":82},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 已完成入库单",
                      "target":{
                        "targetType":"page",
                        "url":"已完成入库单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "18a28b66daf9469fa17b3e6f39bd488c":{
      "scriptId":"u0"},
    "03bc1bec72924f5f8253f2de9f16e304":{
      "scriptId":"u1"},
    "ec597a011b74445db7dcaed7323fc30e":{
      "scriptId":"u2"},
    "10694471815e47bea9a96bb41dc5051b":{
      "scriptId":"u3"},
    "73ffa81779954a218230de9bb323e74d":{
      "scriptId":"u4"}}});