$axure.loadCurrentPage({
  "url":"品牌和仓库选择.html",
  "generationDate":new Date(1479886955894.67),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"61e98040ee91444fb5e6bdf709cce622",
    "type":"Axure:Page",
    "name":"品牌和仓库选择",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5086287f7be74873935c853b1a03a55d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":319,
              "height":567}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edfb2001612247fba2772c9c5d1945d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":319,
                  "height":567}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/品牌和仓库选择/u0.png"}},
{
          "id":"ae11bde0ccd94c3fa8fe3f68b3ca36b8",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":508},
            "size":{
              "width":300,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录后入口页",
                      "target":{
                        "targetType":"page",
                        "url":"登录后入口页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "5086287f7be74873935c853b1a03a55d":{
      "scriptId":"u0"},
    "edfb2001612247fba2772c9c5d1945d3":{
      "scriptId":"u1"},
    "ae11bde0ccd94c3fa8fe3f68b3ca36b8":{
      "scriptId":"u2"}}});