$axure.loadCurrentPage({
  "url":"盘点数量.html",
  "generationDate":new Date(1481113302711.56),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7c8b408db6d0470fabf9c54f28705f11",
    "type":"Axure:Page",
    "name":"盘点数量",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"67d5645f75da4518b7e4297ad8d6d801",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e6286faada84c5a99072d0ff098bede",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/盘点数量/u0.png"}},
{
          "id":"cae4b3b33d9f410ab31ce39f61d757b2",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":259},
            "size":{
              "width":140,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 库区盘点列表",
                      "target":{
                        "targetType":"page",
                        "url":"库区盘点列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "67d5645f75da4518b7e4297ad8d6d801":{
      "scriptId":"u0"},
    "2e6286faada84c5a99072d0ff098bede":{
      "scriptId":"u1"},
    "cae4b3b33d9f410ab31ce39f61d757b2":{
      "scriptId":"u2"}}});