$axure.loadCurrentPage({
  "url":"分拣库区列表.html",
  "generationDate":new Date(1479886956698.62),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"66f2cfdd32364d6bb6e4f3b360547a27",
    "type":"Axure:Page",
    "name":"分拣库区列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"da9c7a9b12394ee4b9e8ccf07e1d13e1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":567}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b876e13ace3f43fea2849716305e2ed0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":567}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣库区列表/u0.png"}},
{
          "id":"0d49373feb2e44f8b4e1e32f4ea9a624",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":80},
            "size":{
              "width":300,
              "height":210}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 待出库物料列表",
                      "target":{
                        "targetType":"page",
                        "url":"待出库物料列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"b9cb35f828ed4734b44d16393a81a2f6",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":400},
            "size":{
              "width":300,
              "height":100}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 待出库物料列表",
                      "target":{
                        "targetType":"page",
                        "url":"待出库物料列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"e323a4628b324c7fb121a7928b4b2ff8",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":510},
            "size":{
              "width":300,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 装箱发货",
                      "target":{
                        "targetType":"page",
                        "url":"装箱发货.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"0927260839a44158a7b80a3e7f97dbd6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":360,
              "y":519},
            "size":{
              "width":300,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed831201136e41888e0f0bef400a04b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":360,
                  "y":519},
                "size":{
                  "width":300,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "da9c7a9b12394ee4b9e8ccf07e1d13e1":{
      "scriptId":"u0"},
    "b876e13ace3f43fea2849716305e2ed0":{
      "scriptId":"u1"},
    "0d49373feb2e44f8b4e1e32f4ea9a624":{
      "scriptId":"u2"},
    "b9cb35f828ed4734b44d16393a81a2f6":{
      "scriptId":"u3"},
    "e323a4628b324c7fb121a7928b4b2ff8":{
      "scriptId":"u4"},
    "0927260839a44158a7b80a3e7f97dbd6":{
      "scriptId":"u5"},
    "ed831201136e41888e0f0bef400a04b3":{
      "scriptId":"u6"}}});