$axure.loadCurrentPage({
  "url":"出库.html",
  "generationDate":new Date(1482148484636.49),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5fa47821a7f443b4a64c61342f425093",
    "type":"Axure:Page",
    "name":"出库",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"07e7cf9025e64f008e40d3cbb1f19c4f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1024,
              "height":768}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b848fdf70d24b62a352ff1cc2d050f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1024,
                  "height":768}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/出库/u0.png"}},
{
          "id":"358719512ca0430183c50cb1b746deac",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":700},
            "size":{
              "width":180,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 历史出库",
                      "target":{
                        "targetType":"page",
                        "url":"历史出库.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"fd0a91492115418aa21942d7cf5dfd1f",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":760,
              "y":10},
            "size":{
              "width":80,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 历史出库",
                      "target":{
                        "targetType":"page",
                        "url":"历史出库.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "07e7cf9025e64f008e40d3cbb1f19c4f":{
      "scriptId":"u0"},
    "0b848fdf70d24b62a352ff1cc2d050f4":{
      "scriptId":"u1"},
    "358719512ca0430183c50cb1b746deac":{
      "scriptId":"u2"},
    "fd0a91492115418aa21942d7cf5dfd1f":{
      "scriptId":"u3"}}});