$axure.loadCurrentPage({
  "url":"发货清单.html",
  "generationDate":new Date(1479886957170.08),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6b5be619a73849279d08172548c499d4",
    "type":"Axure:Page",
    "name":"发货清单",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5d768c6ad40242e0a400298b3eebe8aa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":321,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98217dc407ad4da49c94222ea375bb14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":321,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发货清单/u0.png"}},
{
          "id":"278bb10102f641fb99f4b5af86d117a3",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":510},
            "size":{
              "width":300,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 出库",
                      "target":{
                        "targetType":"page",
                        "url":"出库.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "5d768c6ad40242e0a400298b3eebe8aa":{
      "scriptId":"u0"},
    "98217dc407ad4da49c94222ea375bb14":{
      "scriptId":"u1"},
    "278bb10102f641fb99f4b5af86d117a3":{
      "scriptId":"u2"}}});