$axure.loadCurrentPage({
  "url":"餐品分类筛选.html",
  "generationDate":new Date(1479295313484.65),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"62011f6a6f7b4c1ab8c2d05c806c721b",
    "type":"Axure:Page",
    "name":"餐品分类筛选",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3e363487548847a7af9ab1426d1f5f8b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1024,
              "height":768}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3e76fb7bf0c4f9e8f56ec13f0eb0257",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1024,
                  "height":768}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/餐品分类筛选/u0.jpg"}},
{
          "id":"41ee9e2daebe44f8b2b98926447e8a9b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":350},
            "size":{
              "width":270,
              "height":310}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 餐品订货",
                      "target":{
                        "targetType":"page",
                        "url":"餐品订货.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "3e363487548847a7af9ab1426d1f5f8b":{
      "scriptId":"u0"},
    "f3e76fb7bf0c4f9e8f56ec13f0eb0257":{
      "scriptId":"u1"},
    "41ee9e2daebe44f8b2b98926447e8a9b":{
      "scriptId":"u2"}}});