$axure.loadCurrentPage({
  "url":"发起盘点（手持设备）.html",
  "generationDate":new Date(1481113302677.94),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cf3cebe60d234b3ea7ba4ceaa3bdae54",
    "type":"Axure:Page",
    "name":"发起盘点（手持设备）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0365cf0ee438480295bffb5a779a26d7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c29074bf8cf84e4aabd4c87a46992457",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起盘点（手持设备）/u0.png"}},
{
          "id":"5ff60ec623eb4a48b872eb6e3603a7db",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":20},
            "size":{
              "width":50,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 搜索盘点列表",
                      "target":{
                        "targetType":"page",
                        "url":"搜索盘点列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"d97eb45ce2b64f42a8650e39c7d0a430",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":470},
            "size":{
              "width":300,
              "height":90}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 库区盘点列表",
                      "target":{
                        "targetType":"page",
                        "url":"库区盘点列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "0365cf0ee438480295bffb5a779a26d7":{
      "scriptId":"u0"},
    "c29074bf8cf84e4aabd4c87a46992457":{
      "scriptId":"u1"},
    "5ff60ec623eb4a48b872eb6e3603a7db":{
      "scriptId":"u2"},
    "d97eb45ce2b64f42a8650e39c7d0a430":{
      "scriptId":"u3"}}});