$axure.loadCurrentPage({
  "url":"盘点结果.html",
  "generationDate":new Date(1481113302563.01),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e549f79e712745bc8cae24e948d2aa9b",
    "type":"Axure:Page",
    "name":"盘点结果",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"18c0f99692b24e019b49511872f3a4a4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1920,
              "height":1080}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d81e305d70cb42b389c51b543b3b7d67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1920,
                  "height":1080}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/盘点结果/u0.png"}},
{
          "id":"75e7aec4693c4cdba81716f19ae463f7",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":1420,
              "y":430},
            "size":{
              "width":60,
              "height":120}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 查看备注",
                      "target":{
                        "targetType":"page",
                        "url":"查看备注.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"9069b735e61e4a61ab6610a51ac9c995",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":1420,
              "y":550},
            "size":{
              "width":60,
              "height":420}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 添加备注",
                      "target":{
                        "targetType":"page",
                        "url":"添加备注.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "18c0f99692b24e019b49511872f3a4a4":{
      "scriptId":"u0"},
    "d81e305d70cb42b389c51b543b3b7d67":{
      "scriptId":"u1"},
    "75e7aec4693c4cdba81716f19ae463f7":{
      "scriptId":"u2"},
    "9069b735e61e4a61ab6610a51ac9c995":{
      "scriptId":"u3"}}});