$axure.loadCurrentPage({
  "url":"装箱发货.html",
  "generationDate":new Date(1479886957017.43),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e971122d539741859243c7cd7e21f91d",
    "type":"Axure:Page",
    "name":"装箱发货",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d7b2c45d3dca4c38b556bdd6011beac0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fff7fdc3284467587005c26b4674a98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装箱发货/u0.png"}},
{
          "id":"528621e17b434b1497009133ef300d14",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":509},
            "size":{
              "width":300,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 已添加容器",
                      "target":{
                        "targetType":"page",
                        "url":"已添加容器.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"033de20d24ce4dcc918a3fa6c4d6bebf",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":247,
              "y":22},
            "size":{
              "width":70,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 发货清单",
                      "target":{
                        "targetType":"page",
                        "url":"发货清单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "d7b2c45d3dca4c38b556bdd6011beac0":{
      "scriptId":"u0"},
    "8fff7fdc3284467587005c26b4674a98":{
      "scriptId":"u1"},
    "528621e17b434b1497009133ef300d14":{
      "scriptId":"u2"},
    "033de20d24ce4dcc918a3fa6c4d6bebf":{
      "scriptId":"u3"}}});