$axure.loadCurrentPage({
  "url":"正常完成本单拣货.html",
  "generationDate":new Date(1479886956971.88),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e73aaa0cdedf4f72a688567c189e7af0",
    "type":"Axure:Page",
    "name":"正常完成本单拣货",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b3191b84eaa2411b8b7d70d6f1ecff37",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":319,
              "height":567}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06ebbe3242fb4bdd8de74d3c7921acfa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":319,
                  "height":567}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/正常完成本单拣货/u0.png"}},
{
          "id":"1418f7838fdc4b27b88a60f251c3f3d1",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":330},
            "size":{
              "width":140,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 装箱发货",
                      "target":{
                        "targetType":"page",
                        "url":"装箱发货.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "b3191b84eaa2411b8b7d70d6f1ecff37":{
      "scriptId":"u0"},
    "06ebbe3242fb4bdd8de74d3c7921acfa":{
      "scriptId":"u1"},
    "1418f7838fdc4b27b88a60f251c3f3d1":{
      "scriptId":"u2"}}});