$axure.loadCurrentPage({
  "url":"查询结果.html",
  "generationDate":new Date(1473153211967.26),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7277140683f848b0807ac644d0f0da08",
    "type":"Axure:Page",
    "name":"查询结果",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e288acec52c940a48f0acd66968aaf71",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":-14,
              "y":-10},
            "size":{
              "width":1254,
              "height":890},
            "borderWidth":"2",
            "cornerRadiusTopLeft":"57"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9959c2d2cf642ac9ee0dacc3e1a85ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":-14,
                  "y":-10},
                "size":{
                  "width":1254,
                  "height":890},
                "borderWidth":"2",
                "cornerRadiusTopLeft":"57"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u0.png"}},
{
          "id":"35742510fd804384bf8560cc3d1f6602",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":101,
              "y":50},
            "size":{
              "width":1024,
              "height":768},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9923d80776054aeda7bf2eb4efb2f5ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":101,
                  "y":50},
                "size":{
                  "width":1024,
                  "height":768},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u2.png"}},
{
          "id":"bef73c6b39414272b00f9a96010daf00",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1146,
              "y":400},
            "size":{
              "width":70,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494},
            "cornerRadiusTopLeft":"40"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c40e5b9e59d40a8a511931e30b22ca6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1146,
                  "y":400},
                "size":{
                  "width":70,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494},
                "cornerRadiusTopLeft":"40"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u4.png"}},
{
          "id":"a34a23c9f4ff4b9e9ecc85a090d29e11",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":154,
              "y":101},
            "size":{
              "width":350,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e12fb7f07b47440d9afc24898e518544",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":154,
                  "y":101},
                "size":{
                  "width":350,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查询结果/u6.png"}},
{
          "id":"0669c9871b0a4ec4a5e72d3ecae65940",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":477,
              "y":108},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f821bcf147a4a51b8b1480743eaf605",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":477,
                  "y":108},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u8.png"}},
{
          "id":"fedd67f9e14f4e9791bf64dc857feb87",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":154,
              "y":170},
            "size":{
              "width":936,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/查询结果/u10_line.png"}},
{
          "id":"7122edda4b744b96a6a60011ff39aa49",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":154,
              "y":209},
            "size":{
              "width":936,
              "height":192}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39b714b1b01f430a813bd3446eb2afe7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":136,
                  "height":42},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e7371120375e4a019f7d15f3e7b276c5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"12px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":136,
                      "height":42},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询结果/u12.png"}},
{
              "id":"2af72e8072d4415c88af7b1fea856648",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":42},
                "size":{
                  "width":136,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"67a39af138034977b8941d9890c757e4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":42},
                    "size":{
                      "width":136,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询结果/u22.png"}},
{
              "id":"e2189ae11d6745ebb2bf78af7eb5b290",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":92},
                "size":{
                  "width":136,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fbeaddee02ce4c28aed2d51b07a83988",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":92},
                    "size":{
                      "width":136,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询结果/u22.png"}},
{
              "id":"d80881e927da4970b90832f75a2cf82f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":136,
                  "y":0},
                "size":{
                  "width":302,
                  "height":42},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9b4aa7efa485472a9e8c7fe6688da2da",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"12px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":136,
                      "y":0},
                    "size":{
                      "width":302,
                      "height":42},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询结果/u14.png"}},
{
              "id":"8cc238e80576429981964b40c4409e64",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":136,
                  "y":42},
                "size":{
                  "width":302,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c0a72d3e9e2643a09dedd91b0f99e11f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":136,
                      "y":42},
                    "size":{
                      "width":302,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询结果/u24.png"}},
{
              "id":"1f6e7659b6904507913c395d890b718e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":136,
                  "y":92},
                "size":{
                  "width":302,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"44450d25d9c840fa97f55168ad804820",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":136,
                      "y":92},
                    "size":{
                      "width":302,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询结果/u24.png"}},
{
              "id":"15e22f93cdb14357be0c8dcd8e223dda",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":142},
                "size":{
                  "width":136,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a78bf97cbf06418fadf7a59c7fccd1d9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":142},
                    "size":{
                      "width":136,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询结果/u22.png"}},
{
              "id":"54afa9bf499d47b08f864055c756c376",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":136,
                  "y":142},
                "size":{
                  "width":302,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"06da7e9ac96e4b2cba0177e9c41157ce",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":136,
                      "y":142},
                    "size":{
                      "width":302,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询结果/u24.png"}},
{
              "id":"d792c220ffac45be92ad6aa14aff5a2c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":438,
                  "y":0},
                "size":{
                  "width":148,
                  "height":42},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"da47647746f84b92b925512c9404b826",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"12px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":438,
                      "y":0},
                    "size":{
                      "width":148,
                      "height":42},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询结果/u16.png"}},
{
              "id":"509894903bd54b1e923e65038034df80",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":438,
                  "y":42},
                "size":{
                  "width":148,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1c8272d52af3440d86fed645d18dd262",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":438,
                      "y":42},
                    "size":{
                      "width":148,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询结果/u26.png"}},
{
              "id":"9a0043e95c9d4013bbec8c40fbc91391",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":438,
                  "y":92},
                "size":{
                  "width":148,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"beb955687cac4d9fb9d41a609c14406e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":438,
                      "y":92},
                    "size":{
                      "width":148,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询结果/u26.png"}},
{
              "id":"f69cd277d2674d6f9284e4f588db94c6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":438,
                  "y":142},
                "size":{
                  "width":148,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5fc270af13b04c128ef8ed59a67ec1b4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":438,
                      "y":142},
                    "size":{
                      "width":148,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询结果/u26.png"}},
{
              "id":"b73653eb7f2841e29687717468671868",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":586,
                  "y":0},
                "size":{
                  "width":167,
                  "height":42},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"78919a4b79704862b58e7b1450a87b1c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"12px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":586,
                      "y":0},
                    "size":{
                      "width":167,
                      "height":42},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询结果/u18.png"}},
{
              "id":"da0dd4b564aa43c48dd88849d628b923",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":586,
                  "y":42},
                "size":{
                  "width":167,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d933865c1b12470980bf50cebb67552e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":586,
                      "y":42},
                    "size":{
                      "width":167,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询结果/u28.png"}},
{
              "id":"ebea440976a6417d95b7eb3f3b6d2cc7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":586,
                  "y":92},
                "size":{
                  "width":167,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8fdf6cff14fe4dc3a8616e77ac5cd9af",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":586,
                      "y":92},
                    "size":{
                      "width":167,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询结果/u28.png"}},
{
              "id":"3b825cff8279409aab02883349370053",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":586,
                  "y":142},
                "size":{
                  "width":167,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"04d5f43e7469445f82b45e7a9b3acefc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":586,
                      "y":142},
                    "size":{
                      "width":167,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询结果/u28.png"}},
{
              "id":"d2c4b5cb09974c6e92a53a795d7d39b6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":753,
                  "y":0},
                "size":{
                  "width":183,
                  "height":42},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"62075527b06e4ffc81ae062bc36c5266",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"12px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":753,
                      "y":0},
                    "size":{
                      "width":183,
                      "height":42},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询结果/u20.png"}},
{
              "id":"6c4ffeece6534d86a9b574c4fb7e3e8c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":753,
                  "y":42},
                "size":{
                  "width":183,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bbd8334ddc0a4ca5b00d136c027b3e5d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":753,
                      "y":42},
                    "size":{
                      "width":183,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询结果/u30.png"}},
{
              "id":"d9919eaf25f94d44af02dcabcfee2199",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":753,
                  "y":92},
                "size":{
                  "width":183,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3177f6a119e14c72b071c144927dcc01",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":753,
                      "y":92},
                    "size":{
                      "width":183,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询结果/u30.png"}},
{
              "id":"2ffc1a46611547469d7765b002ee72ad",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":753,
                  "y":142},
                "size":{
                  "width":183,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"15645e0490064ac99287368cfe7b3980",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":753,
                      "y":142},
                    "size":{
                      "width":183,
                      "height":50},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询结果/u30.png"}}]},
{
          "id":"d1db94c03ecd45fe8e454482291e589a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":154,
              "y":300},
            "size":{
              "width":936,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/查询结果/u52_line.png"}},
{
          "id":"b3efe8486c5a45e1926e2afe419b6628",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":154,
              "y":349},
            "size":{
              "width":936,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/查询结果/u52_line.png"}},
{
          "id":"75e9160e40624fd19c3c3ec4d33c6185",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":154,
              "y":400},
            "size":{
              "width":936,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/查询结果/u52_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "e288acec52c940a48f0acd66968aaf71":{
      "scriptId":"u0"},
    "d9959c2d2cf642ac9ee0dacc3e1a85ec":{
      "scriptId":"u1"},
    "35742510fd804384bf8560cc3d1f6602":{
      "scriptId":"u2"},
    "9923d80776054aeda7bf2eb4efb2f5ba":{
      "scriptId":"u3"},
    "bef73c6b39414272b00f9a96010daf00":{
      "scriptId":"u4"},
    "5c40e5b9e59d40a8a511931e30b22ca6":{
      "scriptId":"u5"},
    "a34a23c9f4ff4b9e9ecc85a090d29e11":{
      "scriptId":"u6"},
    "e12fb7f07b47440d9afc24898e518544":{
      "scriptId":"u7"},
    "0669c9871b0a4ec4a5e72d3ecae65940":{
      "scriptId":"u8"},
    "2f821bcf147a4a51b8b1480743eaf605":{
      "scriptId":"u9"},
    "fedd67f9e14f4e9791bf64dc857feb87":{
      "scriptId":"u10"},
    "7122edda4b744b96a6a60011ff39aa49":{
      "scriptId":"u11"},
    "39b714b1b01f430a813bd3446eb2afe7":{
      "scriptId":"u12"},
    "e7371120375e4a019f7d15f3e7b276c5":{
      "scriptId":"u13"},
    "d80881e927da4970b90832f75a2cf82f":{
      "scriptId":"u14"},
    "9b4aa7efa485472a9e8c7fe6688da2da":{
      "scriptId":"u15"},
    "d792c220ffac45be92ad6aa14aff5a2c":{
      "scriptId":"u16"},
    "da47647746f84b92b925512c9404b826":{
      "scriptId":"u17"},
    "b73653eb7f2841e29687717468671868":{
      "scriptId":"u18"},
    "78919a4b79704862b58e7b1450a87b1c":{
      "scriptId":"u19"},
    "d2c4b5cb09974c6e92a53a795d7d39b6":{
      "scriptId":"u20"},
    "62075527b06e4ffc81ae062bc36c5266":{
      "scriptId":"u21"},
    "2af72e8072d4415c88af7b1fea856648":{
      "scriptId":"u22"},
    "67a39af138034977b8941d9890c757e4":{
      "scriptId":"u23"},
    "8cc238e80576429981964b40c4409e64":{
      "scriptId":"u24"},
    "c0a72d3e9e2643a09dedd91b0f99e11f":{
      "scriptId":"u25"},
    "509894903bd54b1e923e65038034df80":{
      "scriptId":"u26"},
    "1c8272d52af3440d86fed645d18dd262":{
      "scriptId":"u27"},
    "da0dd4b564aa43c48dd88849d628b923":{
      "scriptId":"u28"},
    "d933865c1b12470980bf50cebb67552e":{
      "scriptId":"u29"},
    "6c4ffeece6534d86a9b574c4fb7e3e8c":{
      "scriptId":"u30"},
    "bbd8334ddc0a4ca5b00d136c027b3e5d":{
      "scriptId":"u31"},
    "e2189ae11d6745ebb2bf78af7eb5b290":{
      "scriptId":"u32"},
    "fbeaddee02ce4c28aed2d51b07a83988":{
      "scriptId":"u33"},
    "1f6e7659b6904507913c395d890b718e":{
      "scriptId":"u34"},
    "44450d25d9c840fa97f55168ad804820":{
      "scriptId":"u35"},
    "9a0043e95c9d4013bbec8c40fbc91391":{
      "scriptId":"u36"},
    "beb955687cac4d9fb9d41a609c14406e":{
      "scriptId":"u37"},
    "ebea440976a6417d95b7eb3f3b6d2cc7":{
      "scriptId":"u38"},
    "8fdf6cff14fe4dc3a8616e77ac5cd9af":{
      "scriptId":"u39"},
    "d9919eaf25f94d44af02dcabcfee2199":{
      "scriptId":"u40"},
    "3177f6a119e14c72b071c144927dcc01":{
      "scriptId":"u41"},
    "15e22f93cdb14357be0c8dcd8e223dda":{
      "scriptId":"u42"},
    "a78bf97cbf06418fadf7a59c7fccd1d9":{
      "scriptId":"u43"},
    "54afa9bf499d47b08f864055c756c376":{
      "scriptId":"u44"},
    "06da7e9ac96e4b2cba0177e9c41157ce":{
      "scriptId":"u45"},
    "f69cd277d2674d6f9284e4f588db94c6":{
      "scriptId":"u46"},
    "5fc270af13b04c128ef8ed59a67ec1b4":{
      "scriptId":"u47"},
    "3b825cff8279409aab02883349370053":{
      "scriptId":"u48"},
    "04d5f43e7469445f82b45e7a9b3acefc":{
      "scriptId":"u49"},
    "2ffc1a46611547469d7765b002ee72ad":{
      "scriptId":"u50"},
    "15645e0490064ac99287368cfe7b3980":{
      "scriptId":"u51"},
    "d1db94c03ecd45fe8e454482291e589a":{
      "scriptId":"u52"},
    "b3efe8486c5a45e1926e2afe419b6628":{
      "scriptId":"u53"},
    "75e9160e40624fd19c3c3ec4d33c6185":{
      "scriptId":"u54"}}});