$axure.loadCurrentPage({
  "url":"订货.html",
  "generationDate":new Date(1482148484297.18),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"10b5e1fa0c774fa2b7841d4330585fe4",
    "type":"Axure:Page",
    "name":"订货",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f40a30baf65a4c648b93a429a7dc6f68",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1024,
              "height":768}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c24d8741eb24ffea154977203920c16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1024,
                  "height":768}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订货/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f40a30baf65a4c648b93a429a7dc6f68":{
      "scriptId":"u0"},
    "6c24d8741eb24ffea154977203920c16":{
      "scriptId":"u1"}}});