$axure.loadCurrentPage({
  "url":"抽样盘点.html",
  "generationDate":new Date(1473153214057.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"575706cb734c40f787df04980a67fdd1",
    "type":"Axure:Page",
    "name":"抽样盘点",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4139f9eca81c4f09a0873ced20dc177e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":1254,
              "height":890},
            "borderWidth":"2",
            "cornerRadiusTopLeft":"57"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0e20215d025470485cc0c14804b8aa6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":1254,
                  "height":890},
                "borderWidth":"2",
                "cornerRadiusTopLeft":"57"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u0.png"}},
{
          "id":"655109c3e17d4d7383918b5ea68539c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":115,
              "y":60},
            "size":{
              "width":1024,
              "height":768},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2cfe22d3b5143e2a7db696c2d6ab10e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":115,
                  "y":60},
                "size":{
                  "width":1024,
                  "height":768},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u2.png"}},
{
          "id":"a9ac73c6f88b493cad152ba0035b93c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1160,
              "y":410},
            "size":{
              "width":70,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494},
            "cornerRadiusTopLeft":"40"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"849f07621cc6498bb337810b81ed7e47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1160,
                  "y":410},
                "size":{
                  "width":70,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494},
                "cornerRadiusTopLeft":"40"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u4.png"}},
{
          "id":"b2208b3e285b4907addaeb0ba03bedf6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":143,
              "y":161},
            "size":{
              "width":936,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/查询结果/u10_line.png"}},
{
          "id":"9929d8f0529e4f39824ea791f76417cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":143,
              "y":118},
            "size":{
              "width":85,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fe277112df54c87979af670a20a0774",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":143,
                  "y":118},
                "size":{
                  "width":85,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"934fefc3d4f2497792b385bc104507a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":361,
              "y":240},
            "size":{
              "width":500,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebd09c9db3134bd6abb370cfd159bc85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":361,
                  "y":240},
                "size":{
                  "width":500,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u6.png"}},
{
          "id":"3cdf7ab94c33442c8892d01b287c3d63",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":255},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f557b6794a014781a4ab922b30d8e8b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":840,
                  "y":255},
                "size":{
                  "width":10,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/紧急订货/u75.png"}},
{
          "id":"8ed73043332849f786e5b74a00c0912c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":371,
              "y":252},
            "size":{
              "width":92,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de37bbd3a3d2446e84af5daf0c9b0f29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":371,
                  "y":252},
                "size":{
                  "width":92,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05719feb112b46fb97df48804217e7be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":531,
              "y":745},
            "size":{
              "width":160,
              "height":35},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd77fc563f834a7da67a1b537fe5e04b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":531,
                  "y":745},
                "size":{
                  "width":160,
                  "height":35},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/库存预警/u7.png"}},
{
          "id":"3aa1498877bd417c8bffdb0f4c58a32f",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":800},
            "size":{
              "width":10,
              "height":160},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/紧急订货/u65_end.png",
            "line~":"images/紧急订货/u65_line.png"}},
{
          "id":"daa45571418147939615c86d3e254289",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":531,
              "y":968},
            "size":{
              "width":173,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a60c85ded8de4496a3eedbb83f2af34e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":531,
                  "y":968},
                "size":{
                  "width":173,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"11c0fc37d2284aba974da892f1a647c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":359,
              "y":353},
            "size":{
              "width":196,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dd15b1d0cfc41c18784e9fbeeac76d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":359,
                  "y":353},
                "size":{
                  "width":196,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bef35db9f03341468c9cce8d11f431e9",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":290},
            "size":{
              "width":10,
              "height":54},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/紧急订货/u65_end.png",
            "line~":"images/抽样盘点/u22_line.png"}},
{
          "id":"5483cd413102423d9b8864bb8a36be7b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":879,
              "y":258},
            "size":{
              "width":421,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/紧急订货/u87_end.png",
            "line~":"images/抽样盘点/u23_line.png"}},
{
          "id":"9e5225211f524633a970ef29b1388a34",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1310,
              "y":252},
            "size":{
              "width":533,
              "height":147}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10cf421990d24871a64b9664e1539d38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1310,
                  "y":252},
                "size":{
                  "width":533,
                  "height":147}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/抽样盘点/u24.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "4139f9eca81c4f09a0873ced20dc177e":{
      "scriptId":"u0"},
    "c0e20215d025470485cc0c14804b8aa6":{
      "scriptId":"u1"},
    "655109c3e17d4d7383918b5ea68539c7":{
      "scriptId":"u2"},
    "a2cfe22d3b5143e2a7db696c2d6ab10e":{
      "scriptId":"u3"},
    "a9ac73c6f88b493cad152ba0035b93c2":{
      "scriptId":"u4"},
    "849f07621cc6498bb337810b81ed7e47":{
      "scriptId":"u5"},
    "b2208b3e285b4907addaeb0ba03bedf6":{
      "scriptId":"u6"},
    "9929d8f0529e4f39824ea791f76417cb":{
      "scriptId":"u7"},
    "8fe277112df54c87979af670a20a0774":{
      "scriptId":"u8"},
    "934fefc3d4f2497792b385bc104507a2":{
      "scriptId":"u9"},
    "ebd09c9db3134bd6abb370cfd159bc85":{
      "scriptId":"u10"},
    "3cdf7ab94c33442c8892d01b287c3d63":{
      "scriptId":"u11"},
    "f557b6794a014781a4ab922b30d8e8b4":{
      "scriptId":"u12"},
    "8ed73043332849f786e5b74a00c0912c":{
      "scriptId":"u13"},
    "de37bbd3a3d2446e84af5daf0c9b0f29":{
      "scriptId":"u14"},
    "05719feb112b46fb97df48804217e7be":{
      "scriptId":"u15"},
    "fd77fc563f834a7da67a1b537fe5e04b":{
      "scriptId":"u16"},
    "3aa1498877bd417c8bffdb0f4c58a32f":{
      "scriptId":"u17"},
    "daa45571418147939615c86d3e254289":{
      "scriptId":"u18"},
    "a60c85ded8de4496a3eedbb83f2af34e":{
      "scriptId":"u19"},
    "11c0fc37d2284aba974da892f1a647c8":{
      "scriptId":"u20"},
    "2dd15b1d0cfc41c18784e9fbeeac76d6":{
      "scriptId":"u21"},
    "bef35db9f03341468c9cce8d11f431e9":{
      "scriptId":"u22"},
    "5483cd413102423d9b8864bb8a36be7b":{
      "scriptId":"u23"},
    "9e5225211f524633a970ef29b1388a34":{
      "scriptId":"u24"},
    "10cf421990d24871a64b9664e1539d38":{
      "scriptId":"u25"}}});