$axure.loadCurrentPage({
  "url":"完成.html",
  "generationDate":new Date(1479461007910.47),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a17c2de8dd764d598d4b9596cc9ba767",
    "type":"Axure:Page",
    "name":"完成",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5a9d7a2dc74f477a88a64e1fa16cb3c9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1023,
              "height":768}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16ae9bf454bd4d4abb8a1c8c9e15d4f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1023,
                  "height":768}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/完成/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "5a9d7a2dc74f477a88a64e1fa16cb3c9":{
      "scriptId":"u0"},
    "16ae9bf454bd4d4abb8a1c8c9e15d4f1":{
      "scriptId":"u1"}}});