$axure.loadCurrentPage({
  "url":"物料查询.html",
  "generationDate":new Date(1473153211648.95),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"caec0c4cedc549378ae7181e13559694",
    "type":"Axure:Page",
    "name":"物料查询",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ce189ac0b37d4d3b8146250d668b0791",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":1254,
              "height":890},
            "borderWidth":"2",
            "cornerRadiusTopLeft":"57"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a5d2d1159064001b76a386905742bfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":1254,
                  "height":890},
                "borderWidth":"2",
                "cornerRadiusTopLeft":"57"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u0.png"}},
{
          "id":"7e89cacd50eb4a32b748d87301dc7804",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":115,
              "y":60},
            "size":{
              "width":1024,
              "height":768},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ce4834780c141ca84df7345c0a8b42f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":115,
                  "y":60},
                "size":{
                  "width":1024,
                  "height":768},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u2.png"}},
{
          "id":"8141e363d1634e17b502a2ebdc5c60c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1160,
              "y":410},
            "size":{
              "width":70,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494},
            "cornerRadiusTopLeft":"40"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0c0c36be0a24965b2bb385f30f85651",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1160,
                  "y":410},
                "size":{
                  "width":70,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494},
                "cornerRadiusTopLeft":"40"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u4.png"}},
{
          "id":"82133560d863443fa59413536ce23ec1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":380,
              "y":270},
            "size":{
              "width":500,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f33a17cc84664a5681321fb604e9e847",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":380,
                  "y":270},
                "size":{
                  "width":500,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u6.png"}},
{
          "id":"6370be35d8c3430499bcf706ef4564cb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":850,
              "y":280},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21e6862c4e1a4ecfa477f35abd576de9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":850,
                  "y":280},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u8.png"}},
{
          "id":"50f7b32a282540cc9beba67d61b57f7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":587,
              "y":344},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38f4cb108024433e96764f171ce27854",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":587,
                  "y":344},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "ce189ac0b37d4d3b8146250d668b0791":{
      "scriptId":"u0"},
    "8a5d2d1159064001b76a386905742bfb":{
      "scriptId":"u1"},
    "7e89cacd50eb4a32b748d87301dc7804":{
      "scriptId":"u2"},
    "0ce4834780c141ca84df7345c0a8b42f":{
      "scriptId":"u3"},
    "8141e363d1634e17b502a2ebdc5c60c8":{
      "scriptId":"u4"},
    "c0c0c36be0a24965b2bb385f30f85651":{
      "scriptId":"u5"},
    "82133560d863443fa59413536ce23ec1":{
      "scriptId":"u6"},
    "f33a17cc84664a5681321fb604e9e847":{
      "scriptId":"u7"},
    "6370be35d8c3430499bcf706ef4564cb":{
      "scriptId":"u8"},
    "21e6862c4e1a4ecfa477f35abd576de9":{
      "scriptId":"u9"},
    "50f7b32a282540cc9beba67d61b57f7c":{
      "scriptId":"u10"},
    "38f4cb108024433e96764f171ce27854":{
      "scriptId":"u11"}}});