$axure.loadCurrentPage({
  "url":"添加备注.html",
  "generationDate":new Date(1482148484515.89),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1ca76b62e7ba4d1ca3fa80cd7373cc66",
    "type":"Axure:Page",
    "name":"添加备注",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8e0a22a378084b919a71355d5e03824f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1024,
              "height":768}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df839ff982ed4bd089c69095aadb428e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1024,
                  "height":768}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加备注/u0.png"}},
{
          "id":"5224ccc4fad44c4481056f518da9307c",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":340},
            "size":{
              "width":180,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 物料",
                      "target":{
                        "targetType":"page",
                        "url":"物料.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "8e0a22a378084b919a71355d5e03824f":{
      "scriptId":"u0"},
    "df839ff982ed4bd089c69095aadb428e":{
      "scriptId":"u1"},
    "5224ccc4fad44c4481056f518da9307c":{
      "scriptId":"u2"}}});