$axure.loadCurrentPage({
  "url":"登录后入口页.html",
  "generationDate":new Date(1479886955930.2),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ce10fcc04b4747c68ded9074f99a2b6a",
    "type":"Axure:Page",
    "name":"登录后入口页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0e3735414e23474b86ce2c32de419ac9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":319,
              "height":714}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"422d3b63d2a548cf8caf44133bb5c13d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":319,
                  "height":714}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录后入口页/u0.png"}},
{
          "id":"9cb56d560f764c3fa43b2cbe9d948dd8",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":464},
            "size":{
              "width":319,
              "height":120}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 签收",
                      "target":{
                        "targetType":"page",
                        "url":"签收.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"173fa46f6d3e4aceb1147a1b4ca846a9",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":80},
            "size":{
              "width":319,
              "height":120}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 入库",
                      "target":{
                        "targetType":"page",
                        "url":"入库.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"98d500645c4f40d8ae4189afd5c28030",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":594},
            "size":{
              "width":319,
              "height":120}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 上架/移库",
                      "target":{
                        "targetType":"page",
                        "url":"上架_移库.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"48c6e516d5eb43b2ab5958aafd2ddaf4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":340,
              "y":44},
            "size":{
              "width":369,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8828e6c0c8df47f29d5b80a8f1faf40a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":340,
                  "y":44},
                "size":{
                  "width":369,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"801933ccd8b744189ae0d89373f2e16e",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":209},
            "size":{
              "width":319,
              "height":120}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 出库",
                      "target":{
                        "targetType":"page",
                        "url":"出库.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "0e3735414e23474b86ce2c32de419ac9":{
      "scriptId":"u0"},
    "422d3b63d2a548cf8caf44133bb5c13d":{
      "scriptId":"u1"},
    "9cb56d560f764c3fa43b2cbe9d948dd8":{
      "scriptId":"u2"},
    "173fa46f6d3e4aceb1147a1b4ca846a9":{
      "scriptId":"u3"},
    "98d500645c4f40d8ae4189afd5c28030":{
      "scriptId":"u4"},
    "48c6e516d5eb43b2ab5958aafd2ddaf4":{
      "scriptId":"u5"},
    "8828e6c0c8df47f29d5b80a8f1faf40a":{
      "scriptId":"u6"},
    "801933ccd8b744189ae0d89373f2e16e":{
      "scriptId":"u7"}}});