$axure.loadCurrentPage({
  "url":"库存初始化引导页.html",
  "generationDate":new Date(1479461007791.36),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b2cf5ef9e8604b908115305870a6d510",
    "type":"Axure:Page",
    "name":"库存初始化引导页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2e70f06ba9c745f88373daf9e707ee2e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1027,
              "height":768}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3abf8fc758a49419f87ec052858f9d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1027,
                  "height":768}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/库存初始化引导页/u0.png"}},
{
          "id":"5170c733c0444e72a46f18ab25721347",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":488,
              "y":700},
            "size":{
              "width":182,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 物料列表",
                      "target":{
                        "targetType":"page",
                        "url":"物料列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "2e70f06ba9c745f88373daf9e707ee2e":{
      "scriptId":"u0"},
    "c3abf8fc758a49419f87ec052858f9d3":{
      "scriptId":"u1"},
    "5170c733c0444e72a46f18ab25721347":{
      "scriptId":"u2"}}});