$axure.loadCurrentPage({
  "url":"列表搜索.html",
  "generationDate":new Date(1482148485121.46),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"fa20b747c920412aa4af4e5e66533892",
    "type":"Axure:Page",
    "name":"列表搜索",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"db8ab30399094bd2bfeed9d6dde96027",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a525df0247743bd988eb9cef560120b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/列表搜索/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "db8ab30399094bd2bfeed9d6dde96027":{
      "scriptId":"u0"},
    "3a525df0247743bd988eb9cef560120b":{
      "scriptId":"u1"}}});