$axure.loadCurrentPage({
  "url":"物料列表.html",
  "generationDate":new Date(1479461007833.4),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b7806745f400416f82d511972427954c",
    "type":"Axure:Page",
    "name":"物料列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"79135d5c06de424b929a3f4bd94567ec",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1023,
              "height":768}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac59517b356e43d4b341b92339b27bd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1023,
                  "height":768}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料列表/u0.png"}},
{
          "id":"55560f3f01d44f7d9337de03e2685c06",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":488,
              "y":700},
            "size":{
              "width":182,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 完成",
                      "target":{
                        "targetType":"page",
                        "url":"完成.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"fa4157cefbd4400eab3d3bac546bea1b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":860,
              "y":180},
            "size":{
              "width":90,
              "height":500}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 输入数量",
                      "target":{
                        "targetType":"page",
                        "url":"输入数量.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "79135d5c06de424b929a3f4bd94567ec":{
      "scriptId":"u0"},
    "ac59517b356e43d4b341b92339b27bd1":{
      "scriptId":"u1"},
    "55560f3f01d44f7d9337de03e2685c06":{
      "scriptId":"u2"},
    "fa4157cefbd4400eab3d3bac546bea1b":{
      "scriptId":"u3"}}});