$axure.loadCurrentPage({
  "url":"扫码并关联物料.html",
  "generationDate":new Date(1479886956141.91),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4d768885c261411f8b4ea035f37eabaa",
    "type":"Axure:Page",
    "name":"扫码并关联物料",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cf4f8c85e3d14d6fa28d2fb899ee0ad4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":567}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62be2b456150464fbc3926a3380b544c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":567}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/扫码并关联物料/u0.png"}},
{
          "id":"1b5a0ee915d94fe49f6419cfd6047b00",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":262},
            "size":{
              "width":300,
              "height":102}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 关联计量物料",
                      "target":{
                        "targetType":"page",
                        "url":"关联计量物料.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"7686ea6bdd2346d68ead554441d3b122",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":373},
            "size":{
              "width":300,
              "height":193}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 关联计件物料",
                      "target":{
                        "targetType":"page",
                        "url":"关联计件物料.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"2693d547219f47d2962c31e5dbed1857",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":247,
              "y":20},
            "size":{
              "width":70,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 结束本单入库",
                      "target":{
                        "targetType":"page",
                        "url":"结束本单入库.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "cf4f8c85e3d14d6fa28d2fb899ee0ad4":{
      "scriptId":"u0"},
    "62be2b456150464fbc3926a3380b544c":{
      "scriptId":"u1"},
    "1b5a0ee915d94fe49f6419cfd6047b00":{
      "scriptId":"u2"},
    "7686ea6bdd2346d68ead554441d3b122":{
      "scriptId":"u3"},
    "2693d547219f47d2962c31e5dbed1857":{
      "scriptId":"u4"}}});