$axure.loadCurrentPage({
  "url":"入库.html",
  "generationDate":new Date(1473153212622.92),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"555e5a9e88b44518905eb1c32dda4144",
    "type":"Axure:Page",
    "name":"入库",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"564f0bc85eb246e4b8f9570509bb1d1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":1254,
              "height":890},
            "borderWidth":"2",
            "cornerRadiusTopLeft":"57"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48ebf99361174ef5b8061d6d3ea04c9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":1254,
                  "height":890},
                "borderWidth":"2",
                "cornerRadiusTopLeft":"57"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u0.png"}},
{
          "id":"8ee21d0b309b4cc69514e3913286e130",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":115,
              "y":60},
            "size":{
              "width":1024,
              "height":768},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb317731dae04985b13c494dff45feac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":115,
                  "y":60},
                "size":{
                  "width":1024,
                  "height":768},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u2.png"}},
{
          "id":"074a2ab925664729b1daf2ff4d445da3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1160,
              "y":410},
            "size":{
              "width":70,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494},
            "cornerRadiusTopLeft":"40"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f5045c2e79e40449b0580a211c44d7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1160,
                  "y":410},
                "size":{
                  "width":70,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494},
                "cornerRadiusTopLeft":"40"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u4.png"}},
{
          "id":"2dc0a328a8a54763be2e996a3ba350d8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":166,
              "y":253},
            "size":{
              "width":923,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/入库/u6_line.png"}},
{
          "id":"9de2928b710748a4a5a9a9c0d3de2c38",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":253},
            "size":{
              "width":100,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF18A689}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/入库/u7_line.png"}},
{
          "id":"06fb0e7febfa4de6849a7536ab5b5d93",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":223},
            "size":{
              "width":212,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51957c474ef440659c7766abb32ff492",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "size":{
                  "width":106,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5919fb073e814378a4324d1aeb3d987c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "size":{
                      "width":106,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库/u9.png"}},
{
              "id":"3cdd7b2c021642839f071f279e1a3a4b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":106,
                  "y":0},
                "size":{
                  "width":106,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"342b6313dcc94052b5ba74dcaa613741",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":106,
                      "y":0},
                    "size":{
                      "width":106,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/入库/u9.png"}}]},
{
          "id":"1ec2dc5452424ff0a874dba186bf879b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":166,
              "y":283},
            "size":{
              "width":429,
              "height":143},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "outerShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":242,
                "g":242,
                "b":242,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1ec6a5f2638433292b4f8d5d79b2577",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":166,
                  "y":283},
                "size":{
                  "width":429,
                  "height":143},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "outerShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":242,
                    "g":242,
                    "b":242,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入库/u13.png"}},
{
          "id":"77d75c7cd7ec428eaf486b33f5957651",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":172,
              "y":330},
            "size":{
              "width":412,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/入库/u15_line.png"}},
{
          "id":"b9fb5a45773949bcadaaa78a4e8350d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":186,
              "y":302},
            "size":{
              "width":141,
              "height":16},
            "borderWidth":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"026d9c982ed6416fa57f4ecd3dee50f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":186,
                  "y":302},
                "size":{
                  "width":141,
                  "height":16},
                "borderWidth":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"558846b452ea46eda7a8c3507f461277",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":186,
              "y":360},
            "size":{
              "width":174,
              "height":15},
            "borderWidth":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bdc022990294648a0a61946b79715a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":186,
                  "y":360},
                "size":{
                  "width":174,
                  "height":15},
                "borderWidth":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53691265b77d4b4cbdbebea22f0a4c2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":350,
              "y":302},
            "size":{
              "width":59,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d20814a8def4713aeb112e1cf8e855c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":350,
                  "y":302},
                "size":{
                  "width":59,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入库/u20.png"}},
{
          "id":"ef4093feffb54745a2e70d2c0e8358af",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":186,
              "y":385},
            "size":{
              "width":109,
              "height":15},
            "borderWidth":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8e03b61ba7b4525a93158a857e60cea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":186,
                  "y":385},
                "size":{
                  "width":109,
                  "height":15},
                "borderWidth":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37e1a526e8f342959614c979af94ebfd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":660,
              "y":283},
            "size":{
              "width":429,
              "height":143},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad7065557628456ea2875c170ef29c50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":660,
                  "y":283},
                "size":{
                  "width":429,
                  "height":143},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入库/u13.png"}},
{
          "id":"48e4e6b770074a5398ed54f99034268e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":666,
              "y":330},
            "size":{
              "width":412,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/入库/u15_line.png"}},
{
          "id":"d2d0fc1814f44ad3b4c18e17c4f1ad0d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":680,
              "y":302},
            "size":{
              "width":141,
              "height":16},
            "borderWidth":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05cfad4d429e4c539bdaf61c921cbe8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":680,
                  "y":302},
                "size":{
                  "width":141,
                  "height":16},
                "borderWidth":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f672aa946d434ca18e4a77ace12666c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":680,
              "y":360},
            "size":{
              "width":174,
              "height":15},
            "borderWidth":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a191333b30a45f18b83451b150a6bc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":680,
                  "y":360},
                "size":{
                  "width":174,
                  "height":15},
                "borderWidth":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57e204e298854a8691a50480cf5c003b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":844,
              "y":302},
            "size":{
              "width":59,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33ce140a6d7148a18112abf981384421",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":844,
                  "y":302},
                "size":{
                  "width":59,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入库/u20.png"}},
{
          "id":"2f6b934cc6ec46b1a4e5cf117db82cf7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":680,
              "y":389},
            "size":{
              "width":109,
              "height":15},
            "borderWidth":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"645b505581df4f9cb81138d0cacc3f2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":680,
                  "y":389},
                "size":{
                  "width":109,
                  "height":15},
                "borderWidth":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a1212ac95104af980cd07a940ffbda1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":166,
              "y":92},
            "size":{
              "width":350,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"491a9720fc724b3ab91429f3978307ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":166,
                  "y":92},
                "size":{
                  "width":350,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查询结果/u6.png"}},
{
          "id":"14a8ffc629d04758943615acbcc1e6fa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":489,
              "y":99},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fa548dd962e47219d3cf0a60fbf9f16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":489,
                  "y":99},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物料查询/u8.png"}},
{
          "id":"f5271f0570d44bc992e9fd14f572e3a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":166,
              "y":148},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a64bcfca4c8b4f31954775d2678029d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":166,
                  "y":148},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc9a1c174cda41c7b4b00c2b2a68ec1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":225,
              "y":148},
            "size":{
              "width":124,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"047c23e173c2444ea75f3f674809594b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":225,
                  "y":148},
                "size":{
                  "width":124,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d2ddcac3f751456cb23a75a6920467f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":166,
              "y":178},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c72d27b472094f6b9d7da9067c9fd536",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":166,
                  "y":178},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1257e39268cd46c587075dd4f4c1e1fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":225,
              "y":178},
            "size":{
              "width":247,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9dc0877111804a309600587a848ed46b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":225,
                  "y":178},
                "size":{
                  "width":247,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "564f0bc85eb246e4b8f9570509bb1d1c":{
      "scriptId":"u0"},
    "48ebf99361174ef5b8061d6d3ea04c9c":{
      "scriptId":"u1"},
    "8ee21d0b309b4cc69514e3913286e130":{
      "scriptId":"u2"},
    "bb317731dae04985b13c494dff45feac":{
      "scriptId":"u3"},
    "074a2ab925664729b1daf2ff4d445da3":{
      "scriptId":"u4"},
    "0f5045c2e79e40449b0580a211c44d7e":{
      "scriptId":"u5"},
    "2dc0a328a8a54763be2e996a3ba350d8":{
      "scriptId":"u6"},
    "9de2928b710748a4a5a9a9c0d3de2c38":{
      "scriptId":"u7"},
    "06fb0e7febfa4de6849a7536ab5b5d93":{
      "scriptId":"u8"},
    "51957c474ef440659c7766abb32ff492":{
      "scriptId":"u9"},
    "5919fb073e814378a4324d1aeb3d987c":{
      "scriptId":"u10"},
    "3cdd7b2c021642839f071f279e1a3a4b":{
      "scriptId":"u11"},
    "342b6313dcc94052b5ba74dcaa613741":{
      "scriptId":"u12"},
    "1ec2dc5452424ff0a874dba186bf879b":{
      "scriptId":"u13"},
    "b1ec6a5f2638433292b4f8d5d79b2577":{
      "scriptId":"u14"},
    "77d75c7cd7ec428eaf486b33f5957651":{
      "scriptId":"u15"},
    "b9fb5a45773949bcadaaa78a4e8350d1":{
      "scriptId":"u16"},
    "026d9c982ed6416fa57f4ecd3dee50f8":{
      "scriptId":"u17"},
    "558846b452ea46eda7a8c3507f461277":{
      "scriptId":"u18"},
    "8bdc022990294648a0a61946b79715a7":{
      "scriptId":"u19"},
    "53691265b77d4b4cbdbebea22f0a4c2c":{
      "scriptId":"u20"},
    "5d20814a8def4713aeb112e1cf8e855c":{
      "scriptId":"u21"},
    "ef4093feffb54745a2e70d2c0e8358af":{
      "scriptId":"u22"},
    "a8e03b61ba7b4525a93158a857e60cea":{
      "scriptId":"u23"},
    "37e1a526e8f342959614c979af94ebfd":{
      "scriptId":"u24"},
    "ad7065557628456ea2875c170ef29c50":{
      "scriptId":"u25"},
    "48e4e6b770074a5398ed54f99034268e":{
      "scriptId":"u26"},
    "d2d0fc1814f44ad3b4c18e17c4f1ad0d":{
      "scriptId":"u27"},
    "05cfad4d429e4c539bdaf61c921cbe8d":{
      "scriptId":"u28"},
    "f672aa946d434ca18e4a77ace12666c3":{
      "scriptId":"u29"},
    "3a191333b30a45f18b83451b150a6bc9":{
      "scriptId":"u30"},
    "57e204e298854a8691a50480cf5c003b":{
      "scriptId":"u31"},
    "33ce140a6d7148a18112abf981384421":{
      "scriptId":"u32"},
    "2f6b934cc6ec46b1a4e5cf117db82cf7":{
      "scriptId":"u33"},
    "645b505581df4f9cb81138d0cacc3f2a":{
      "scriptId":"u34"},
    "4a1212ac95104af980cd07a940ffbda1":{
      "scriptId":"u35"},
    "491a9720fc724b3ab91429f3978307ab":{
      "scriptId":"u36"},
    "14a8ffc629d04758943615acbcc1e6fa":{
      "scriptId":"u37"},
    "1fa548dd962e47219d3cf0a60fbf9f16":{
      "scriptId":"u38"},
    "f5271f0570d44bc992e9fd14f572e3a7":{
      "scriptId":"u39"},
    "a64bcfca4c8b4f31954775d2678029d2":{
      "scriptId":"u40"},
    "cc9a1c174cda41c7b4b00c2b2a68ec1d":{
      "scriptId":"u41"},
    "047c23e173c2444ea75f3f674809594b":{
      "scriptId":"u42"},
    "d2ddcac3f751456cb23a75a6920467f7":{
      "scriptId":"u43"},
    "c72d27b472094f6b9d7da9067c9fd536":{
      "scriptId":"u44"},
    "1257e39268cd46c587075dd4f4c1e1fc":{
      "scriptId":"u45"},
    "9dc0877111804a309600587a848ed46b":{
      "scriptId":"u46"}}});